### ISSUE TITLE
casper.click() = "nonexistent selector" but exists

### ISSUE THREAD

**Issue by fleebzz** [casperjs/casperjs#378] opened 2013-02-11 10:54 UTC
I have a problem with the casper.click() method.

Consider this HTML source code :

``` html
<!DOCTYPE html>
<html>
<head>
  <title>"nonexistent selector" but exists</title>
</head>

<body>
  <div></div>
  <div>
    <div>
      <ul>
        <li>
          <div>
            <span>
              <span>
                <a href="/my-link">My link</a>
              </span>
            </span>
          </div>
        </li>
      </ul>
    </div>
  </div>
</body>
</html>
```

Consider Casper test :

``` javascript

var casper = require('casper').create({
    verbose: true,
    logLevel: "debug"
});

casper.test.comment('"nonexistent selector" but exists');

casper.start('http://localhost/bug_casper');

casper.then(function(){
  this.evaluate(function(){
    console.log(document.querySelector('html > body > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1) > a:nth-child(1)').innerHTML);
  });
});

casper.then(function(){
  casper.click('html > body > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1) > a:nth-child(1)');
});

casper.run(function () {
    this.test.done();
});
```

I have following output :

``` bash
# "nonexistent selector" but exists
[info] [phantom] Starting...
[info] [phantom] Running suite: 4 steps
[debug] [phantom] opening url: http://localhost/bug_casper, HTTP GET
[debug] [phantom] Navigation requested: url=http://localhost/bug_casper, type=Other, lock=true, isMainFrame=true
[debug] [phantom] Navigation requested: url=http://localhost/bug_casper/, type=Other, lock=true, isMainFrame=true
[debug] [phantom] url changed to "http://localhost/bug_casper/"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Step 3/4 http://localhost/bug_casper/ (HTTP 301)
[info] [remote] My link
[info] [phantom] Step 3/4: done in 307ms.
[info] [phantom] Step 4/4 http://localhost/bug_casper/ (HTTP 301)
[debug] [phantom] Mouse event 'click' on selector: html > body > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1) > a:nth-child(1)
FAIL CasperError: Cannot dispatch click event on nonexistent selector: html > body > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1) > a:nth-child(1)
#    type: uncaughtError
#    error: "CasperError: Cannot dispatch click event on nonexistent selector: html > body > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1) > a:nth-child(1)"
CasperError: Cannot dispatch click event on nonexistent selector: html > body > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > span:nth-child(1) > a:nth-child(1)
  /Users/bez/Workspaces/test_casper:1144 in mouseEvent
  /Users/bez/Workspaces/test_casper:390 in click
  /Users/bez/Workspaces/test_casper/bug_casper.js:18
  /Users/bez/Workspaces/test_casper:1329 in runStep
  /Users/bez/Workspaces/test_casper:332 in checkStep
```

We see line 11 of the output : 

``` bash
[info] [remote] My link
```

Which means casper can find the link in the page with evaluate() method but not from casper.click() method.

I checked on W3C and this HTML is valid.

Thanks in advance.

**Comment by istr** [comment] 2015-12-02 19:23
It seems that [the phantomjs bug is fixed with 2.0.0](https://github.com/ariya/phantomjs/issues/11632#issuecomment-116047307).

Now that we have phantomjs2 support in master, could you please verify if this fixes the problem with CasperJS, too?

Thanks a lot.

**Comment by istr** [comment] 2015-12-02 19:24
We should add a hint in the documentation that this problem might occur with all supported phantomjs 1.9.x versions.

**Comment by amerikan** [comment] 2016-02-16 19:48
Still seems to be happening for me with phantomjs 2.1.1 and casperjs 1.1.0-beta5. Has anyone else tested it?

**Comment by dgreene1** [comment] 2016-08-16 16:47
> Still seems to be happening for me with phantomjs 2.1.1 and casperjs 1.1.0-beta5. Has anyone else tested it?

Yes, the problem is still occurring in 2.1.1

**Comment by awcchungster** [comment] 2017-05-20 20:57
I'm seeing this with Phantomjs 2.1.1 and CasperJS 1.1.4. 

Does anyone still get this bug?

**Comment by jefleponot** [comment] 2017-05-22 14:24
@awcchungster 

It is not really a bug
Only visible element can be clicked...

**Comment by jefleponot** [comment] 2017-05-22 14:26
I will propose a new PR to propose a solution

**Comment by prcongithub** [comment] 2017-09-23 16:07
I am also facing this problem now. Anybody got this working?

**Comment by dgreene1** [comment] 2017-09-25 13:34
Maybe consider using `cypress` instead. CasperJS isn't gonna last now that PhantomJS is being phased out.

**Comment by Hipska** [comment] 2017-11-02 14:06
Really? Just moved from Cypress to CasperJS as it seems to fit better our use case.

I seem to have similar situation:
```js
        test.assertExists(x('//a[contains(text(),"consumption")]'));        
        casper.mouseEvent('mouseover', x('//a[contains(text(),"consumption")]'));
```
Results in the following:
```
PASS Find an element matching: xpath selector: //a[contains(text(),"consumption")]
[error] [remote] mouseEvent(): Couldn't find any element matching 'xpath selector: //a[contains(text(),"consumption")]' selector
[warning] [phantom] Mouse.processEvent(): no native fallback for type mouseover
```

**Comment by kensoh** [comment] 2018-07-26 03:58
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.

**Closed by kensoh** 2018-07-26 03:58 UTC
Labels: ARCHIVE, Documentation, PhantomJS
