### ISSUE TITLE
Add Better Samples to Help Users Getting Started.

### ISSUE THREAD

**Issue by istr** [casperjs/casperjs#1532] opened 2016-04-13 17:17 UTC
As a recent hot discussion and a look into the open issues show, we should think about better samples and documentation to get users started.

While there are scores of good samples, code snippets, and even testing modules building on top of CasperJS out in the wild, we see lots of false issues filed against CasperJS (basically all those tagged "Help Request") and some [frustrated users turning their back on CasperJS before they even got started](https://github.com/n1k0/casperjs/issues/1530). From my own experience I remember that the "learning curve" to get a grip on CasperJS is not as flat as it could be.

Being totally aware that CasperJS is by no means a "point-and-click" solution, maybe we should
- try to add some sort of primer with basic "DOs" and "DON'Ts"
- add some more complex examples that work on / with popular JS frameworks (e.g. angular, react to name a few)
- try to optimize the guidance / initial path through the existing documentation

Ping @mickaelandrieu, @BIGjuevos, @jefleponot for thoughts and input.

**Comment by BIGjuevos** [comment] 2016-04-13 17:26
I agree.  I can take on some backbone and angular example apps.

- I think the lowest hanging fruit is the Quick Start and optimizing it.
- Is it worth updating the casperjs.org homepage to encourage people to go through an improved quick start?

**Comment by istr** [comment] 2016-04-13 17:34
> worth updating the casperjs.org homepage

Definitely. It could help to give a better guidance using 
- less links
- a few simple steps, e.g.
  1. download
  2. quickstart
  3. samples / primer
- improve on the weight (and position in the page) the links have according to relevance for newcomers

**Comment by mickaelandrieu** [comment] 2016-04-13 18:38
Agree too.  I will suggest a new article on "how can you debug a CasperJS script?"

**Comment by BIGjuevos** [comment] 2016-04-24 09:03
So, as you can tell by the timestamp, I got some inspiration to give the homepage a revamp and gave it a quick go.  Let me know what you think @istr @mickaelandrieu 

First draft, what do you guys think?

![](http://i.imgur.com/ctKXU8i.png)

**Comment by istr** [comment] 2016-04-24 09:50
Looks good... I would remove the ```-g``` flag from the npm install command though, because you can do a quick test without super-user rights with a local installation.

**Comment by ianchanning** [comment] 2016-05-06 21:09
Is there a reason why the documentation typically leaves out the first line:

```javascript
var casper = require('casper').create();
```

There are quite a few scripts that are almost self contained, i.e. they have 

```javascript
casper.start('...');
...
casper.run();
```

But then anyone learning can't just copy and paste and run that script they always have to add in the first line.

I see @BIGjuevos using the same again in the [home page revamp](https://github.com/casperjs/casperjs/issues/1532#issuecomment-213918051).

**Comment by BIGjuevos** [comment] 2016-05-06 22:00
@ianchanning When using `casperjs test <file/path>` you don't need to include `var casper = require('casper').create()` since that is done for you.

There is a desire to redo the quickstart as well.  This would be a good thing to bring into consideration.

**Comment by ianchanning** [comment] 2016-05-07 21:16
@BIGjuevos ah, ok very useful to know. The first section though is just calling `casperjs sample.js` though? It's also under the 'Navigation and Automation' section rather than 'Testing', so shouldn't be called with the `test` argument anyway?

![screenshot from 2016-05-07 22 37 35-cropped](https://cloud.githubusercontent.com/assets/233318/15094552/8790328a-14a7-11e6-9bf2-0894de39fd67.png)

**Comment by BIGjuevos** [comment] 2016-05-07 21:29
@ianchanning Wonderful catch.  I've updated it and the pull request.  You can see the updated index html at: https://github.com/BIGjuevos/casperjs/blob/gh-pages/index.html

It would be awesome if you could turn your precise eye to a new quick start guide.  It would be good, and hopefully we can address some common questions and set better examples in the docs.

**Comment by BIGjuevos** [comment] 2016-05-07 21:31
Also, I've gone and done the copy paste thing, and confirmed that all examples on the page work once phantom is installed.

**Comment by ianchanning** [comment] 2016-05-08 16:41
@BIGjuevos would it be worth switching the defaut site you suggest to scrape to be wikipedia instead of google? Where as it's certainly not illegal, google certainly [don't like automated access to their search results](http://stackoverflow.com/questions/22657548/is-it-ok-to-scrape-data-from-google-results). Nor are they open source. Doing a search for casperjs on the wikipedia home page would give you similar results.

My current project is scraping David Bowie's discography which is kinda fun :)

**Comment by mickaelandrieu** [comment] 2016-05-08 18:09
Better,  we should scrape casperjs website instead :)  Wikipedia do recommend to not scrape their data but download their database,  I don't want to annoy another OSS community!

**Comment by ianchanning** [comment] 2016-05-08 18:33
Yep, sounds good, search the casperjs documentation with the casperjs documentation. Gloriously meta :)

**Comment by istr** [comment] 2016-05-11 17:58
> Better, we should scrape casperjs website instead

Yes, good idea. Let us do some self-scraping. :smile:

**Comment by BIGjuevos** [comment] 2016-05-11 18:03
Luckily, the new version of the website is available for updates within the codebase.  I look forward to the pull request.

In the meantime, I think the next two highest priorities are:
1. Improved quickstart guide.
2. Examples of how to test these darn fancy new modern web apps.

**Comment by Thebigbignooby** [comment] 2017-03-08 17:11
a good guide on getting a working environnement set up would be really helpful.

I have tried many times in the past two years to use casperjs but everytime I give up because playing around with paths and understanding which executable to run is frustrating...

**Comment by kensoh** [comment] 2017-05-20 02:39
Hi @Thebigbignooby have you seen this? http://docs.casperjs.org/en/latest/installation.html

I used this and it looks like covering the setup for various platforms. I've used this guide when installing  CasperJS on macOS, Linux, and Windows.

**Comment by kensoh** [comment] 2017-08-18 00:40
Closing this as the PRs for the docs have been merged pretty long ago :smile:

**Closed by kensoh** 2017-08-18 00:40 UTC
Labels: Documentation, General Discussion
