### ISSUE TITLE
Using assertNotVisible to ensure selector does not exist throws ail to find element matching selector error

### ISSUE THREAD

**Issue by rails4sandeep** [casperjs/casperjs#1360] opened 2015-11-27 03:54 UTC
I am using `assertNotVisible` test assertion to verify that the selector no longer exist, but the test throws an error `FAIL Fail to find element matching selector: selector`

``` javascript
verifyNotVisible: function (test, selector) {
    casper.then(function () {
      test.assertNotVisible(selector);
    });
  }
```

**Comment by istr** [comment] 2015-11-27 08:35
Please provide
- a minimal working test (your html, your selector that fails)
- the CasperJS version
- the engine version
you are using to make this reproducible on our side.

**Comment by kensoh** [comment] 2017-05-24 00:48
@rails4sandeep thanks for raising this! It looks like the issue has been fixed along the way. Closing this but do ping here if anything :)

When I run on an invalid missing selector I get `PASS Selector is not visible`.

If I run on something that exists and is really visible I get `FAIL Selector is not visible`

**Closed by kensoh** 2017-05-24 00:48 UTC
