### ISSUE TITLE
<deleted> Popup in casper.popup after popup is closed

### ISSUE THREAD

**Issue by TitanNitWeb** [casperjs/casperjs#1717] opened 2016-11-14 11:43 UTC
Hi,

If you have more than one popup in an iframe and check it with casper.withPopup(...) you get an Error.
(Open Popup 1 -> Close Popup 1 -> Open Popup 2 -|->Error)

I have figuered out that casper.popups first element is in an undefined status (neither null nor undefined or something it is "<deleted>").

To solve this problem you can make something like this:

`casper.on('popup.loaded', function(webPage) {
	for(vari=0;i<casper.popups.length;i++){//for each popup in the array
		try{
			JSON.stringify(casper.popups[i]);		//if <deleted> it is not readable an throw an Error
		}catch(e){
			casper.popups.splice(i,1); //delete the <deleted> object from the array
		}
	}
});`

**Comment by jefleponot** [comment] 2016-11-15 16:12
Hi @TitanNitWeb 
Could you propose a PR ?

Regards
JEF

**Comment by luqmansungkar** [comment] 2016-11-18 08:45
Just discovered this issue today after struggling with it for a few days, and I think the problem is in the `findByRegExp` and `findByURL` function in `pagestack.js`. Specifically in line where it check if the regex or the url match the popup url, it will throw an error because it can't access the url from the deleted popupPage object.

It can be fixed by changing the implementation to something like this :

```
var popup = this.filter(function(popupPage) {
    try{
	    return regexp.test(popupPage.url);
    }catch(e){
    	return false;
    }
})[0];
```

**Comment by TitanNitWeb** [comment] 2016-11-29 15:27
I have also never done a PR. Both solutions don't solve the problem to 100%. I have to test an web-application with many popups and "casper.popup" is very instable.

**Comment by jefleponot** [comment] 2016-11-30 09:15
Hi @luqmansungkar and @TitanNitWeb, 

Yours experiences in popup management are important for all contributors.
Could you please write one or more tests that reproduce bugs thaht you have encountered ?

1. Fork the casperJS project to have your own github repo
2. clone casperJS project on your PC with a git command : git clone https://github.com/casperjs/casperjs.git
3. add a new branch : git checkout -b popupTestsFix
4. update  file test in tests/suites/casper/popup.js or add a new file
5. write you test code
5. check bugs with command: casper selftest tests/suites/casper/popup.js
6. commit : git add file -m "comment"
7. push to your githup account : git push forkname popupTestsFix
8. click on githup fork to propose this PR 
:smile: 

Next step , you could propose an enhancement with the same method (I could help you if you want)

**Comment by TitanNitWeb** [comment] 2016-12-14 14:54
Okay,
I have written a test which forces the error and also implemented the solution within this test.
The file is called multiplepopups.js ...
I have problems since point 8 and don't know if something is committed and if it is the right account.
I had problems adding the html files which are required for this test...
So I have made a zip with the files (added here) feel free to take this file (js-file belongs to tests/suites/casper/, html to tests/site/)
[casperjs.zip](https://github.com/casperjs/casperjs/files/652022/casperjs.zip)

**Comment by jefleponot** [comment] 2016-12-15 16:28
@TitanNitWeb , nice job,

I rewiew your test : 
- SLIMERJS 0.10.02 : PASS 27 tests AND Freeze
- PHANTOMJS 1.9.7 : FAIL 29 tests executed in 1.955s, 27 passed, 2 failed, 0 dubious, 0 skipped.
- PHANTOMJS 2.1.1 : PASS 30 tests executed in 1.174s, 30 passed, 0 failed, 0 dubious, 0 skipped.

**Comment by jefleponot** [comment] 2016-12-23 09:10
I found the main error.

When an event closes a window or a popup, CasperJS continue to do treatments on the closed page (with the "evaluate" method). So PhantomJS < 2 crashes and SlimerJS crashes.

```error
FAIL Error: WebPage not opened 
#    type: uncaughtError 
#    file: tests/suites/casper/multiplepopups.js 
#    error: {} 
#    stack: not provided
```

In the "casper.evaluate" method, it never checks if "WebPage" is opened or closed => that is not great.

In your instance, you close all popups because they have the same url :-1: but it doesn't matter.

**Comment by xm0625** [comment] 2017-02-22 16:28
Anyone is solving this bug? I  have been trapped for a few days......
(casperjs 1.1.4 + phantomjs 2.1.1 / slimerjs 0.10.0)

start and close popup for a few times, I saw the following error.
phantomjs engine report this:
Error: cannot call function of deleted QObject    
slimerjs engine report this:
Error onClosing: []  (undefined ; line:192 col:0) 
Error onClosing: [TypeError] casper.page is null (file:///usr/local/lib/node_modules/casperjs/modules/casper.js ; line:2642 col:1)

**Comment by jefleponot** [comment] 2017-02-22 19:45
Hi @xm0625,

Could you please send your code ? We could try to reproduce bug ...
Thank you for advance

**Comment by xm0625** [comment] 2017-02-23 04:49
Thanks @jefleponot , here is the script.
[issus_post.7z.zip](https://github.com/casperjs/casperjs/files/795567/issus_post.7z.zip)

**Comment by jefleponot** [comment] 2017-03-04 15:24
@xm0625 Thank you

**Comment by xm0625** [comment] 2017-03-04 15:29
@jefleponot 
maybe I sloved the bug.
replace
https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L2664
to
if (casper.page && (casper.page.id === closedPopup.id)) {

**Comment by xm0625** [comment] 2017-03-04 15:44
@jefleponot 
but the popup is still hard to use.
I have to record the id of the popup at the "popup.created" event  listener(function), 
and then, intercept each popup of casper.popups to get the index of target popup in casper.popups array.
just like.... 
casper.withPopup(findPopupById(popupPageId), function () {...})
It's not vary elegant.

**Comment by xm0625** [comment] 2017-03-04 15:57
I noticed that when I open&close&open the popup, there are one more items in the  casper.popups array (the <deleted> object? closed WebPage(QtObject?) to be destroyed or recycled?).
actually, if I ensure only one popup opened at one time, 
"casper.withPopup(0, function () {...})" should work well.

**Comment by jefleponot** [comment] 2017-03-06 21:24
你好 @xm0625 , i found the problem . Could you please update casperJS and try again ..
thank you for advance.

**Comment by kensoh** [comment] 2017-08-17 23:26
Closing the issue for now as the patches have been merged, and no feedback on issues for a few months. But do reopen if anything!

**Closed by kensoh** 2017-08-17 23:26 UTC
Labels: 2 - Working, Bug
