### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'casper.cli.get')

### ISSUE THREAD

**Issue by 0fork** [casperjs/casperjs#1333] opened 2015-10-12 09:57 UTC
I've been testing Phantom 2.0 support (phantomjs2 branch) and I'm getting `TypeError: undefined is not an object (evaluating 'casper.cli.get')` error. I tried to trace and fix it but I can't find where the problem is. This happens with all scripts requiring CLI input like https://github.com/n1k0/casperjs/blob/master/samples/screenshot.js for example.

**Comment by istr** [comment] 2015-12-02 21:05
Please retry against current master (we added 2.0 support recently) and report back if your problem persists.

**Comment by kensoh** [comment] 2017-05-24 00:57
Hi @0fork thanks for raising! It's been a while and it seems that the issue is now resolved. I tried running with v1.1.4 and v2.1.1 and got the following outputs + correct screenshot created. Closing the issue but do ping if you run into anything :)

```
casperjs a.js tebelorg a.png
Saved screenshot of https://twitter.com/tebelorg to a.png
```

**Closed by kensoh** 2017-05-24 00:57 UTC
