### ISSUE TITLE
Casperjs does not step into evaluate remote page environment during remote debugging

### ISSUE THREAD

**Issue by skihappy** [casperjs/casperjs#705] opened 2013-11-13 21:56 UTC
Just discovered remote interactive debugging with casperjs and phantomjs. Tested it out and the result that it works perfect in phantomjs and half way with casperjs. Casper does not step into the remote environment inside a evaluate function where phantom does. Did anybody else have that issue. Is there a workaround or is it just me. Attached are casper and phantom scripts I used for testing. Commands I used are <pre> phantomjs --remote-debugger-port=9001 casper_test.js</pre> and   <pre>phantomjs --remote-debugger-port=9001 phantom_test.js</pre>

casperjs test script:

``` js
phantom.casperPath = '/usr/local/src/casperjs';
phantom.injectJs(phantom.casperPath + '/bin/bootstrap.js');

var casper_options=
    {
        clientScripts:  ['/home/dmitry/.javascript/jquery/jquery-1.10.2.js'],
        logLevel: 'info',
        verbose: true,
        viewportSize:{width: 1280, height: 800}
    };

casper = require('casper').create(casper_options);
casper.start('http://google.com/');
debugger;
casper.then(function() {
    console.log('Started');
    debugger;
    this.page.evaluate(function(){
        debugger;
        a=1;
    });
});
casper.then(function() {
    console.log('continue');
    debugger;
    this.page.evaluate(function(){
        debugger;
        a=2;
    });
});
casper.run(function(){
    this.exit();
});
```

phantomjs test script

``` js
var page = require('webpage').create(),
    system = require('system'),
    t, address;
debugger;
if (system.args.length === 1) {
    console.log('Usage: loadspeed.js <some URL>');
    phantom.exit();
}
debugger;
t = Date.now();
address = system.args[1];
page.open(address, function (status) {
    page.evaluate(function(){
        debugger;
        console.log('here');
        var a=0;
        var b=9;
    });
    if (status !== 'success') {
        console.log('FAIL to load the address');
    } else {
        t = Date.now() - t;
        console.log('Loading time ' + t + ' msec');
    }
    phantom.exit();
});
```

**Comment by nagakiran** [comment] 2015-05-16 19:05
I am also facing this issue. Is there any work around?

**Comment by hajpoj** [comment] 2016-09-27 21:00
try `casperjs --remote-debugger-port=9001 casper_test.js` (instead of `phantomjs`)
Check out this too: https://drupalize.me/blog/201410/using-remote-debugger-casperjs-and-phantomjs

In the debugger on `localhost` You might have to go to the `sources` tab and enable remote debugging for all sessions and refresh to get the debugger to halt on a `debugger;` line

**Comment by kensoh** [comment] 2017-06-02 03:00
Hi @skihappy and @nagakiran I'm a CasperJS user for couple of years, looking through open issues. May I check if @hajpoj 's recommendation works for you?

**Comment by kensoh** [comment] 2017-06-02 04:55
@skihappy and @nagakiran closing this issue for now but do reopen if the issue is still happening for you. Thanks for raising this! I'm on GitHub most days, but reachable on ken@tebel.org if I somehow missed your reply.

**Closed by kensoh** 2017-06-02 04:55 UTC
