### ISSUE TITLE
Three selftest failures on Windows with beta4

### ISSUE THREAD

**Issue by mepard** [casperjs/casperjs#1427] opened 2016-02-04 20:38 UTC
These pass on Mac OS X.

```
...
Test file: C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/casper/encode.js
# base64encode() and download() tests
PASS base64encode() and download() tests (2 tests)
FAIL Casper.base64encode() can retrieve base64 contents
#    type: assertEquals
#    file: C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/casper/encode.js
#    subject: 0
#    expected: 6160
...
Test file: C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/casper/logging.js
# logging tests
PASS logging tests (4 tests)
PASS Casper.log() adds a log entry
PASS ClientUtils.log() adds a log entry
PASS ClientUtils.log() adds a log entry at a given level
FAIL Casper.log() logged messages
#    type: assertEquals
#    file: C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/casper/logging.js
#    subject: 4
#    expected: 3
...
Test file: C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/http_status.js
# HTTP status code handling
PASS HTTP status code handling (163 tests)
FAIL file:// protocol does not set a HTTP status
#    type: assertHttpStatus
#    file: C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/http_status.js
#    subject: false
#    current: 200
#    expected: null
...
FAIL 1017 tests executed in 22.954s, 1014 passed, 3 failed, 0 dubious, 5 skipped.

Details for the 3 failed tests:

In C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/casper/encode.js
  base64encode() and download() tests
    assertEquals: Casper.base64encode() can retrieve base64 contents
In C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/casper/logging.js
  logging tests
    assertEquals: Casper.log() logged messages
In C:/Users/Marc/Downloads/n1k0-casperjs-1.1-beta4-0-g3aa6f76/n1k0-casperjs-3aa6f76/tests/suites/http_status.js
  HTTP status code handling
    assertHttpStatus: file:// protocol does not set a HTTP status
```

**Comment by istr** [comment] 2016-02-04 21:16
Which engine version (PhantomJS) do you use?

**Comment by istr** [comment] 2016-02-04 22:12
Confirmed Win10 PhantomJS 2.1.1 from https://github.com/istr/casperjs/tree/hotfix/windows-binary (current master with binary re-compiled).

**Comment by mepard** [comment] 2016-02-04 22:18
Sorry. That was with the current master, now reporting 2.2.0-development. I just tested with the current download, 2.1.1, and the same happens.

**Comment by istr** [comment] 2016-02-04 22:26
Confirmed Win10 PhantomJS 1.9.6 (oh my, is that slow compared to 2.1.1).

The problem is, that we can't use travis to test on windows automatically (only the mono-based tests for linux and OS/X that are obviously rather pointless).

**Comment by mepard** [comment] 2016-02-04 22:39
OT: While I was reproducing this, I had one where a bunch of tests reported  `FAIL CasperError: evaluate() requires javascript to be enabled`.

I ran it again and didn't have those. Any idea why?

**Comment by istr** [comment] 2016-02-05 11:00
> a bunch of tests reported FAIL CasperError: evaluate() requires javascript to be enabled

This is another intermittent I see from time to time, too (all platforms) when the platform is under high load condition.

**Comment by istr** [comment] 2016-02-05 12:05
I am ```git bisect``` ing this now using PhantomJS 1.9.6 to find the root cause.

**Comment by cosmini** [comment] 2016-04-08 23:30
Same problem on Windows 10 (x64) with `CasperJS version 1.1.0-beta5 using phantomjs version 2.1.1`

**Comment by kensoh** [comment] 2017-08-18 01:55
Closing this for now as the latest are v1.1.4ish but do reopen if anything!

**Closed by kensoh** 2017-08-18 01:55 UTC
Labels: Bug, Windows
