### ISSUE TITLE
No return status from casper.download() calls

### ISSUE THREAD

**Issue by west1012** [casperjs/casperjs#1006] opened 2014-08-12 19:52 UTC
I'm loving CasperJS so far, but I'm having issues with `casper.download()`.  Specifically, two things:

1) There is no way to check the success or failure of a `casper.download()` call.

2) `casper.on('downloaded.file', targetPath)` returns the _attempted_ `targetPath`, regardless of whether the file was successfully downloaded or not.  This seems like it's the wrong behavior to me (but perhaps it isn't?)

To illustrate where I'm running into problems with these issues, I occasionally I get errors like the following, even when I have `--web-security=no` set in the command line arguments:

```
[warning] [remote] getBinary(): Unfortunately, casperjs cannot make cross domain ajax requests
[error] [remote] getBinary(): Error while fetching /secure/api/report?documentID=2185-VL_20140523_VLSM_AXDX_20453_01-5K9T21M2ETCVPGUCP6F81F0ODQ: Error: NETWORK_ERR: XMLHttpRequest Exception 101
```

Having these errors isn't a big deal to me, since I can just retry the download and generally the download will work the second time (or third time, if need be) around.

However, there's no way that I can tell of to get the return status to see whether I should retry or not.  Even `casper.currentHTTPStatus` doesn't seem to work (it's "200" every time I check it).

I dug into the code a bit.  Here's the code for `casper.download()`:

```
Casper.prototype.download = function download(url, targetPath, method, data) {
    "use strict";
    this.checkStarted();
    var cu = require('clientutils').create(utils.mergeObjects({}, this.options));
    try {
        fs.write(targetPath, cu.decode(this.base64encode(url, method, data)), 'wb');
        this.emit('downloaded.file', targetPath);
        this.log(f("Downloaded and saved resource in %s", targetPath));
    } catch (e) {
        this.log(f("Error while downloading %s to %s: %s", url, targetPath, e), "error");
    }
    return this;
};
```

Perhaps something could be set in the `catch (e) { ... }` block?

Thanks for your help on this.  (And sorry if I missed something or I'm not following proper protocol here.  I'm new to both GitHub and JavaScript.  And CasperJS.)

**Comment by daviidesnow** [comment] 2016-02-18 13:23
got the same issue downloading large files via casperjs. are there any ideas to fix this?

**Comment by west1012** [comment] 2016-02-18 14:20
Sorry for the bad news, but I ended up using a different solution.

**Comment by istr** [comment] 2016-02-18 14:38
> Sorry for the bad news, but I ended up using a different solution.

Would be nice to know which one... :-)

**Comment by west1012** [comment] 2016-02-18 14:45
It's been a while, but I think I ended up using some form of casperjs to
get the URLs for the files plus python's BeautifulSoup to actually download
the files.  As a coder I wasn't happy with the solution at all, but I only
needed to use the two scripts together once and it got the job done.

Best of luck!  And sorry I couldn't be more help.

**Comment by daviidesnow** [comment] 2016-02-19 12:05
hey guys. i started looking into the code and the functions relatet to `casper.download();`. then i tried several ways with the `XMLHttpRequest()` function using `casper.evaluate();`. then i figured out some simple fix which worked for me. i just added one line to the `sendAJAX()` function in [clientutils.js](https://github.com/n1k0/casperjs/blob/master/modules/clientutils.js). the only thing i changed was adding `if (xhr.status != 200) return '';` at line 800.

i have not a great experience working with git and contributing directly with that repository. also i am not sure if my "fix" is best practice. so never the less i would share my "solution". hopefully some experienced developer would get this together to implement it to the master branch?

just for reference the whole `sendAJAX()` function, with my change:
```
        this.sendAJAX = function sendAJAX(url, method, data, async, settings) {
            var xhr = new XMLHttpRequest(),
                dataString = "",
                dataList = [];
            method = method && method.toUpperCase() || "GET";
            var contentType = settings && settings.contentType || "application/x-www-form-urlencoded";
            xhr.open(method, url, !!async);
            this.log("sendAJAX(): Using HTTP method: '" + method + "'", "debug");
            if (settings && settings.overrideMimeType) {
                xhr.overrideMimeType(settings.overrideMimeType);
            }
            if (method === "POST") {
                if (typeof data === "object") {
                    for (var k in data) {
                        dataList.push(encodeURIComponent(k) + "=" + encodeURIComponent(data[k].toString()));
                    }
                    dataString = dataList.join('&');
                    this.log("sendAJAX(): Using request data: '" + dataString + "'", "debug");
                } else if (typeof data === "string") {
                    dataString = data;
                }
                xhr.setRequestHeader("Content-Type", contentType);
            }
            xhr.send(method === "POST" ? dataString : null);
            // waiting for xhr status
            if (xhr.status != 200) return '';
            return xhr.responseText;
        };
```

**Comment by istr** [comment] 2016-02-19 12:44
@daviidesnow Ok, it seems that you got to the root cause of the issue. In fact, the handling of error conditions in ```sendAJAX``` should be improved. However, just checking for ```200``` is not enough (there are other "successful" return codes) and faking an empty responseText will not help to detect if the download actually succeeded.

**Comment by daviidesnow** [comment] 2016-02-19 12:54
yes, you are right. so it is a "dirty" fix and just works for my needs, at the moment. maybe it would be a better way to return an object containing the `response `and `statuscode`. maybe it would be also better using `onreadystatechange` and wait for `readyState == 4 (DONE)`?

**Comment by alexamy** [comment] 2016-03-18 00:29
Hi guys! Solution that helped me (first line of code):

`var casper = require('casper').create({
  pageSettings: {
    webSecurityEnabled: false
  }
});`

Tried to use command line option `casperjs --web-security=no`, but it DIDN'T work, though have same functionality as code above.

**Comment by istr** [comment] 2016-03-18 20:51
> maybe it would be also better using onreadystatechange and wait for readyState == 4 (DONE)?

IMHO that would be the way to go (check for ```4 === readyState```). @daviidesnow Could you imagine to prepare a PR for that?

**Comment by daviidesnow** [comment] 2016-03-30 07:26
@istr i have not done this before but i will give it a try. it would be lasting a while ... looking for git tutorials and best coding practices now :)

**Comment by etchen99** [comment] 2017-05-10 16:26
In addition, is there a reason why `getBinary` (which is used by `download`) fails silently?

https://github.com/casperjs/casperjs/blob/4c0929ac574d53df08534d03b215b20e1f9ed0f1/modules/clientutils.js#L393-L406

It would be nice to be able to have an error event be emitted from that when there are failures.

**Comment by kensoh** [comment] 2017-05-30 17:31
Tagging on a new pull request which adds a new event for 'fileDownloadError' - https://github.com/casperjs/casperjs/pull/1835

**Comment by kensoh** [comment] 2017-08-18 02:24
Closing the issue as there's a new event for this. Also, maybe using waitForExec combined with curl can help handle different edge cases with file downloading. Do reopen if anything!

**Closed by kensoh** 2017-08-18 02:24 UTC
