### ISSUE TITLE
frames with id but without name

### ISSUE THREAD

**Issue by jszczypk** [casperjs/casperjs#1865] opened 2017-08-03 14:28 UTC
Hi,

<frame id="abc">
   <html>
   <body><button>OK</button></body>
   </html>
</frame>

casper.withFrame("abc") { function() {
    casper.clickLabel("OK");
  }
}

Code inside casper.withFrame("abc") fails when trying to access any element with CasperError: No element matching selector found: xpath selector: (//frame|//iframe)[@name="abc"]

Frame is found using id = "abc", but then Casper is trying to access elements using frame[name].

Regards,
Janusz

**Comment by kensoh** [comment] 2017-08-03 16:09
Hi @jszczypk this is by design, the withFrame method supports searching by name or by the frame number. http://docs.casperjs.org/en/latest/modules/casper.html#withframe

Can you try replacing with a number to denote which frame is it in the DOM? It does not support searching by @id identifier now. Probably that design is enough at the point when the method was written. Otherwise there are so many different ways of identifying the frame. Changing to support XPath will allow all the different ways to be used, but I think the original design tries to make it easier by only specifying the name instead of a full XPath.

Adding code reference from casper.js -
https://github.com/casperjs/casperjs/blob/a30162945d79cce7a664b17b576a5271ef1d7d9f/modules/casper.js#L2301

```js
Casper.prototype.switchToChildFrame = function switchToChildFrame(frameInfo) {
"use strict";
if (utils.isNumber(frameInfo)) {
if (frameInfo > this.page.childFramesCount() - 1) {
throw new CasperError(f('Frame number "%d" is out of bounds.', frameInfo));
        }
this.page.context = this.getElementBounds(selectXPath('(//frame|//iframe)[' + (frameInfo + 1) + ']'), true);
    } else if (this.page.childFramesName().indexOf(frameInfo) === -1) {
throw new CasperError(f('No frame named "%s" was found.', frameInfo));
    } else {
this.page.context = this.getElementBounds(selectXPath('(//frame|//iframe)[@name="' + frameInfo + '"]'), true);
    }
// make the frame page the currently active one
this.page.switchToFrame(frameInfo);
```

**Comment by jszczypk** [comment] 2017-08-03 17:55
Thank you for a detailed answer.
Yes, addressing frames using frame number works without problems.

I have reported it as it is inconsistent. withFrame should report an error when frame can't be addressed with name or the callback function should be able to address elements with frame's id.

IMHO this.page.context = this.getElementBounds(selectXPath('(//frame|//iframe)[@name="' + frameInfo + '"]'), true); should be changed to allow for both name and id. I am not good at writing XPATHs but it should be something like '((//frame|//iframe)[@name="' + frameInfo + '"]|(//frame|//iframe)[@id="' + frameInfo + '"])'

**Comment by kensoh** [comment] 2017-08-03 18:08
Thanks Janusz for adding on! The error message of not found is ok, and matches documentation link above which shows using name or number. But I get what you mean..

In fact, for a web automation project I'm working on base on CasperJS, I made headless Chrome integration. And I added code something like what you typed (you can put @name = "abc" or @id "abc" inside the square brackets to combine the XPath) for the headless Chrome integration. Why I add, because I find many times, there are websites not using name for frame but only id, so gotta add that to make it work.

The problem with adding @name is, next time there will be something else, eg by class, or by css selector for example. Also for BC, it be impossible to allow full XPath directly in query. There is workaround, by detecting / or ( as first character because XPath starts with these 2 characters, but it is not fool proof. Not sure what is best way to address, I do think adding id support is a good idea.

(tagging @jefleponot who is maintaining CasperJS for inputs)

**Comment by kensoh** [comment] 2018-03-16 01:20
Bumping -

**Comment by kensoh** [comment] 2018-07-26 03:33
Closing the issue as CasperJS, like PhantomJS, is not being actively maintained. But do continue discussion if any! Workaround is to hack the .switchToChildFrame function to allow selection other than using name.

**Closed by kensoh** 2018-07-26 03:33 UTC
