### ISSUE TITLE
assertSelectorDoesntHaveText -- Fail message has incorrect wording

### ISSUE THREAD

**Issue by rmhines** [casperjs/casperjs#1377] opened 2015-12-17 20:35 UTC
The fail message for assertSelectorDoesntHaveText reads 'FAIL Did not find "Bad text here' within the selector "p#myId"'. The fail condition is met when the text is found, so this message doesn't make sense. It should say something like 'FAIL found text "Lorem Ipsem" within...'

**Comment by kensoh** [comment] 2017-05-24 01:44
Hi @rmhines thanks for raising this! This is still the behavior today. It looks like the assertions statement is the expected behavior. During run-time the result PASS or FAIL appears. I do think this design is appropriate by setting the expected result as example and labelling PASS/FAIL.

It should make tracking easier than having 2 types of descriptions depending on status of test. Also, there is option to provide own message for the test which may be useful to display something more contextual for the test. It's a design question, though for me as test automation engineer this is ok as long consistent for the assertions set.

```FAIL Did not find "About" within the selector "footer"```

**Comment by kensoh** [comment] 2017-05-25 01:38
@rmhines closing this for now as this design looks standardized but do ping if you would like to add on with more inputs. I'm on GitHub almost everyday these days or you can email me ken@tebel.org

**Closed by kensoh** 2017-05-25 01:38 UTC
