### ISSUE TITLE
waitFor*() has a very unclear behaviour

### ISSUE THREAD

**Issue by nerder** [casperjs/casperjs#1491] opened 2016-03-21 11:26 UTC
Hello guys,
Is about one day that i'm trying to understand how all the `waitFor*()` functions are suppose to work.
This is my example implementation

``` javascript
var casper = require('casper').create({
  remoteScripts:  [
    'http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js',
    'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.6.1/lodash.js'
  ],
  pageSettings: {
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.1500.71 Safari/537.36'
  },
  viewport: {
    width: 1280,
    height: 1024
  },
  waitTimeout: 60000,
  logLevel: 'debug',
  verbose: true
});

casper.start('https://web.whatsapp.com/', function(){
    this.echo('Starting...')
    this.waitForSelector(".qrcode", (function() {
        this.captureSelector(filename, "html");
        this.echo("Saved screenshot of " + (this.getCurrentUrl()) + " to " + filename);
    }), (function() {
        this.echo(this.getHTML());
        this.die("Timeout reached. Fail whale?");
        this.exit();
    }), 15000);
});

casper.run();
```

What i'm expecting here, is that `waitForSelector()` will continuously fetch the DOM, until it will not found the `<div class="qrcode"></div>` in a certain amount of time (15s in that example), but actually what it seems to do, is just loading the page after 15s and check if there is or not that selector, that actually i don't get why this will be useful (if not for some WAF avoiding that don't like to receive a lot of request in a short time). Than if `waitingFor*()` is not what i'm looking for, what i can use to accomplish this task? I have a working implementation using PhantomJS and `setTimeout()`, but i'm looking for something smarter.

Any Clue? Am i missing something?

Check even my SO question: http://stackoverflow.com/questions/36128875/casperjs-waitfor-has-very-unclear-behaviour

Thank you in advance

cc @istr , @mickaelandrieu , @paazmaya , @n1k0

**Comment by nerder** [comment] 2016-03-21 17:32
Actually i finally found out what this issue is about and is related to this one  #1068

Under MacOSX for some reason installing `PhantomJS` and `CasperJS` using `homebrew` will install and outdated version of Phantom (1.9.8) that still have that issue.
I fixed removing phantom and casper and reinstalling them using npm.

We should open an issue to `homebrew` about this issue.

**Comment by BIGjuevos** [comment] 2016-03-21 18:15
@nerder Looks like there is already an [open PR up ](https://github.com/Homebrew/homebrew/pull/38632) over at homebrew.

Pinging @n1k0 for insight on the status of phantomjs2.

**Comment by n1k0** [comment] 2016-03-21 18:24
You guys need to take over this PR or send a new one to update the brew package with the expected dependencies. At the time I was handling this, it was rather easy because there was a single supported version of phantom, but now... (no mention of slimerjs btw)

**Comment by istr** [comment] 2016-04-13 17:42
> with the expected dependencies

Ok, let's have a look into that. The current releases stopped auto-installing any PhantomJS version at all (exactly because of the nearly unsolvable problem to choose the correct engine version for every situation), so we should update the brew packaging to reflect this.

**Comment by kensoh** [comment] 2017-05-21 20:12
This looks to be ok now. CasperJS latest brew is 1.1.4 with PhantomJS 2.11 dependency.

TA:tagui.sikuli kensoh$ brew info casperjs 
casperjs: stable 1.1.4 (bottled), HEAD
Navigation scripting and testing tool for PhantomJS
http://www.casperjs.org/
/usr/local/Cellar/casperjs/1.1-beta4 (378 files, 16.2MB)
  Built from source on 2016-03-25 at 08:53:03
/usr/local/Cellar/casperjs/1.1.3 (284 files, 7MB)
  Poured from bottle on 2016-09-05 at 17:05:21
/usr/local/Cellar/casperjs/1.1.4 (294 files, 7MB) *
  Poured from bottle on 2017-03-14 at 09:13:41
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/casperjs.rb
==> Dependencies
Required: ***phantomjs*** ✔
==> Requirements
Required: macOS >= 10.6 ✔
TA:tagui.sikuli kensoh$ brew info phantomjs
***phantomjs: stable 2.1.1*** (bottled), HEAD
Headless WebKit scriptable with a JavaScript API
http://phantomjs.org/
/usr/local/Cellar/phantomjs/2.1.1 (49 files, 50.5MB) *
  Poured from bottle on 2016-03-25 at 09:44:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/phantomjs.rb
==> Dependencies
Required: openssl ✔
==> Requirements
Build: git ✔, xcode ✘
Required: macOS >= 10.7

**Comment by kensoh** [comment] 2017-05-23 23:41
Thanks @nerder for raising this! I saw your thumbs up. I'm a CasperJS user for couple of years. Browsing through open issues now to see if anything I can help with. Closing this for now as the issue is resolved, and don't think saw a recurrence of this topic of package and dependencies issue in the open issues. But do ping if anything :)

**Closed by kensoh** 2017-05-23 23:41 UTC
Labels: Packaging
