### ISSUE TITLE
Casperjs / Phantomjs : Resource request error: "Network Error - Operation Canceled Error"

### ISSUE THREAD

**Issue by wiiilllll** [casperjs/casperjs#1859] opened 2017-07-27 07:38 UTC
Hello,

I am a beginner on casper/phantomjs and I am trying to do a simple example.

Please find a part of my code below:

```
var casper = require("casper").create({
});

var id=1333;
var selector = 'div[data-entry-id^="'+id+'"]';

var errors = [];
casper.on( 'page.error', function (msg, trace) {
  this.echo("Error:    " + msg, "ERROR");
  this.echo("file:     " + trace[0].file, "WARNING");
  this.echo("line:     " + trace[0].line, "WARNING");
  this.echo("function: " + trace[0]["function"], "WARNING");
  errors.push(msg);
});

var resourceErrors=[];
casper.on('resource.received', function(resource) {
    var status = resource.status;
    if(status >= 400) {
        casper.log('Resource ' + resource.url + ' failed to load (' + status + ')', 'error');
        resourceErrors.push({
            url: resource.url,
            status: resource.status
        });
    }
});

casper.start("http://jeuconcoursphotos.hscampaigns.com/#entry-"+id, function() {
    this.waitForSelector(selector, (function() {
        this.echo('location is ' + this.getCurrentUrl() );
    }), (function() {
        this.die("Timeout reached. Fail whale?");
        this.exit();
    }), 120000);

});

var nb;
casper.then(function() {
   nb = this.evaluate(function(sel) {
        var elements = __utils__.findAll(sel);
        //console.log("elements"+elements);
        return elements.map(function(e) {
            return e.getAttribute('data-vote-num');
        });
    },selector);
});

casper.run(
        function() {
           this.echo("votes :"+JSON.stringify(nb)).exit();

             if (errors.length > 0) {
                    this.echo(errors.length + ' Javascript errors found', "WARNING");
             } else {
                    this.echo(errors.length + ' Javascript errors found', "INFO");
             }

             if(resourceErrors.length > 0){
                   this.echo(resourceErrors.length + ' resourceErrors found', "WARNING");
             } else {
                this.echo(resourceErrors.length + ' resourceErrors found', "INFO");
             }
        }
);
```

When I launch the following command:

> casperjs check-vote.js --debug=true --ignore-ssl-errors=yes --ssl-protocol=any

I have following errors 'Resource request error: QNetworkReply::NetworkError(OperationCanceledError) ( "Operation canceled" )' at the end of the test. How can I fix this to have no errors in logs?

```2017-07-25T10:49:10 [DEBUG] WebPage - evaluateJavaScript result QVariant(QVariantList, (QVariant(QString, "5")))
votes :["5"]
0 Javascript errors found
0 resourceErrors found
2017-07-25T10:49:10 [DEBUG] WebPage - setupFrame ""
2017-07-25T10:49:10 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(OperationCanceledError) ( "Operation canceled" ) URL: "https://bam.nr-data.net/1/dfd35c7377?a=12009886&v=998.365d633&to=Z1cBZhNXDERZBkZYWF4dIlEVXw1ZFzFaVFpVcQxcFUQNW1QAQHFTWUETXgBPIVhWEVdCQw%3D%3D&rst=11448&ref=http://jeuconcoursphotos.hscampaigns.com/&ap=305&be=741&fe=10391&dc=8144&af=err,xhr,ins&perf=%7B%22timing%22:%7B%22of%22:1500972539328,%22n%22:0,%22f%22:1,%22dn%22:1,%22dne%22:1,%22c%22:1,%22ce%22:1,%22rq%22:1,%22rp%22:1,%22rpe%22:919,%22dl%22:730,%22di%22:8885,%22ds%22:8885,%22de%22:9241,%22dc%22:11124,%22l%22:11131,%22le%22:11141%7D,%22navigation%22:%7B%7D%7D&at=SxACEFtNH0o%3D&jsonp=NREUM.setToken"
2017-07-25T10:49:10 [DEBUG] WebPage - updateLoadingProgress: 10
2017-07-25T10:49:10 [DEBUG] WebPage - setupFrame ""
2017-07-25T10:49:10 [DEBUG] WebPage - updateLoadingProgress: 100
2017-07-25T10:49:10 [DEBUG] WebPage - setupFrame ""
2017-07-25T10:49:10 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2017-07-25T10:49:10 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2017-07-25T10:49:10 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2017-07-25T10:49:10 [DEBUG] WebPage - updateLoadingProgress: 10
2017-07-25T10:49:10 [DEBUG] WebPage - setupFrame ""
2017-07-25T10:49:10 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2017-07-25T10:49:10 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2017-07-25T10:49:10 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2017-07-25T10:49:10 [DEBUG] WebPage - updateLoadingProgress: 100
2017-07-25T10:49:10 [DEBUG] CookieJar - Saved "_ga=GA1.2.8135132.1500972549; expires=Thu, 25-Jul-2019 08:49:08 GMT; domain=.hscampaigns.com; path=/"
2017-07-25T10:49:10 [DEBUG] CookieJar - Saved "_gid=GA1.2.1353459247.1500972549; expires=Wed, 26-Jul-2017 08:49:08 GMT; domain=.hscampaigns.com; path=/"
2017-07-25T10:49:10 [DEBUG] CookieJar - Saved "_gat_brightkit=1; expires=Tue, 25-Jul-2017 08:50:08 GMT; domain=.hscampaigns.com; path=/"
2017-07-25T10:49:10 [DEBUG] CookieJar - Saved "brightkit_session=eyJpdiI6IjFOY2g2SjBHSlh5cWowQjU5cGJ2U01pQVZOYm1jK3VHcG9ZWXRRRjFJQjQ9IiwidmFsdWUiOiJcL0hPVlVhZGJjK2srOEZEOWVXYWorQ2J1YnNGZnA5SGh1M1FONjhZSkFHTlBvMXpuQWNJNDQrRkcwWFwveTVPRGdZNU15Yzg1d1czWkhlR1dUV1hsMjhRPT0iLCJtYWMiOiJmMDE0NDYxYTg1NTg4MjNmMmYzMTMxNWI3MjZmMmNhNmFjNmIyYzk2MTVhYTZiM2E4N2Y4ZWJjOGFmY2MyMzM3In0%3D; HttpOnly; expires=Tue, 25-Jul-2017 10:49:08 GMT; domain=.hscampaigns.com; path=/"
```

> phantomjs -v 2.1.1

> casperjs --version 1.1.4

**Comment by kensoh** [comment] 2017-07-27 16:13
Hi @wiiilllll I tried replicating by running your script and can see the same network error message. 

It looks like an error message returned by PhantomJS, not sure what is the cause and why the message appears for your script. Not sure if the issue can be raised at PhantomJS repo or any users here have similar experience to share their tips. Also copying @jefleponot maintainer for CasperJS.

```
2017-07-28T00:07:19 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(OperationCanceledError) ( "Operation canceled" ) URL: "https://bam.nr-data.net/1/dfd35c7377?a=12009886&v=998.365d633&to=Z1cBZhNXDERZBkZYWF4dIlEVXw1ZFzFaVFpVcQxcFUQNW1QAQHFTWUETXgBPIVhWEVdCQw%3D%3D&rst=11905&ref=http://jeuconcoursphotos.hscampaigns.com/&ap=426&be=1027&fe=9709&dc=4455&af=err,xhr,ins&perf=%7B%22timing%22:%7B%22of%22:1501171627938,%22n%22:0,%22f%22:0,%22dn%22:0,%22dne%22:0,%22c%22:0,%22ce%22:0,%22rq%22:0,%22rp%22:0,%22rpe%22:1223,%22dl%22:1023,%22di%22:5482,%22ds%22:5482,%22de%22:5539,%22dc%22:10733,%22l%22:10736,%22le%22:10740%7D,%22navigation%22:%7B%7D%7D&at=SxACEFtNH0o%3D&jsonp=NREUM.setToken"
```

**Comment by wiiilllll** [comment] 2017-07-27 19:16
Ok thanks for your reply and for your try.
Hope someone will have an answer.

**Comment by kensoh** [comment] 2017-07-27 21:39
Welcome @wiiilllll I googled and found that there's an open PhantomJS issue on this error, and a number of people are experiencing this - https://github.com/ariya/phantomjs/issues/12750

**Comment by jefleponot** [comment] 2017-07-28 07:50
Hi @wiiilllll 

Just add these listener to your code : 

```js
casper.on('resource.error', function(resource) {
   console.log(JSON.stringify(resource,null,4));
});
```

and you will see that the url https://bam.nr-data.net/... that is called by jeuconcoursphotos.hscampaigns.com doesn't exist .
In searching a little with the "whois" command , I found that the correct url is **http://bam-9.nr-data.net/...**

PhantomJS just shows you that your site contains errors 😄 

Regards 
jef

**Comment by wiiilllll** [comment] 2017-07-28 09:29
Hi @kensoh @jefleponot 

Thank you for your help. I can move forward with that.

Regards.

**Comment by jefleponot** [comment] 2017-07-28 13:51
@wiiilllll Please close the issue

**Closed** 2017-07-28 22:32 UTC
