### ISSUE TITLE
Window alert isn't catched by Casper in onbeforeunload when there's error in script

### ISSUE THREAD

**Issue by Wirone** [casperjs/casperjs#833] opened 2014-02-17 12:07 UTC
_It's related to #416 a little bit._

I know what was wrong. Regardless to our script and issue with logic, there's a problem with CasperJS and `onbeforeunload`. You can see it here:

https://gist.github.com/Wirone/9048945

If `alert()` is invoked inside `onbeforeunload`'s function, and if there is a error in script, CasperJS throws alert popup to windows environment even if `casper.on('remote.alert')` is defined.

Is it supposed to work this way?

PS. In our script alert popup was thrown even without an error. The issue was doubled navigation - `casper.click()` + `casper.open()` on an anchor which was opening new window. Developer did it this way because it "worked", instead of changing `target` to `_self` (after this change popup doesn't show). I can't give you those script because they're company's property, but "environment" is really similar - `onbeforeunload` with `alert()` and additionally returning string value, anchor opening page in new window and casper's logic with click + open. I can't reproduce it in simple way because there was some custom MouseEvent included. No matter what is the case, alert should not "physically" go to the user.

**Comment by kensoh** [comment] 2017-06-02 02:42
Hi @Wirone I'm a CasperJS user for couple of years, browsing through open issues. Is this still happening for you using CasperJS v1.1.4 and PhantomJS v2.1.1? I haven't come across other open issues on this and I don't have a Windows laptop at the moment to verify if this still happens.

**Comment by kensoh** [comment] 2017-06-02 04:55
@Wirone closing this issue for now but do reopen if the issue is still happening for you. Thanks for raising this! I'm on GitHub most days, but reachable on ken@tebel.org if I somehow missed your reply.

**Closed by kensoh** 2017-06-02 04:55 UTC

**Comment by Wirone** [comment] 2017-06-02 09:37
I have checked my gist with CasperJS 1.1.4 @ PhantomJS 2.1.1 and the output is:

```
-> % casperjs start.js
Remote alert: Just alerting...
[load.finished] success
Waiting.
[load.finished] success
Waiting.
ReferenceError: Can't find variable: notExistingFunction
  <path>/phantomjs:/code/start.js:30
  <path>/phantomjs:/platform/casper.js:2368 in _check
```

Alert is not thrown, so I assume it's ok now, but it was so long time ago that I don't remember fully what was going on :-)

**Comment by kensoh** [comment] 2017-06-02 11:14
Hi @Wirone thanks for your update and taking time to retest this issue! :smile:
