### ISSUE TITLE
Binding issue with slimer 0.10

### ISSUE THREAD

**Issue by Huulivoide** [casperjs/casperjs#1607] opened 2016-05-31 12:32 UTC
Trying to run anything with current casper master and slimer 0.10/master will result in the following error:
[Exception] TypeError: this.filter is not a function filename:file:///foo/casperjs/modules/casper.js  line:677

I am not sure if this is a bug in Casper or Slimer.
Slimer bug: https://github.com/laurentj/slimerjs/issues/491

How to reproduce on Linux (tested on Arch Linux):

git clone https://github.com/casperjs/casperjs.git
git clone https://github.com/laurentj/slimerjs.git
curl https://download-installer.cdn.mozilla.net/pub/firefox/releases/46.0.1/linux-x86_64/en-US/firefox-46.0.1.tar.bz2 | tar xj
export SLIMERJSLAUNCHER="$(pwd)/firefox/firefox"
export PATH="$(pwd)/slimerjs/src/:$PATH"
./casperjs/bin/casperjs --engine=slimerjs selftest

**Comment by paazmaya** [comment] 2016-06-02 06:10
Same issue in Mac, CasperJS 1.1.1, SlimerJS 0.10.0

**Comment by mlalpho** [comment] 2016-06-11 19:56
I'm not hitting this during selftest `xvfb-run casperjs --engine=slimerjs selftest --log-level=debug --verbose=true`
```
 casperjs --version
1.1.1
```
```
 slimerjs --version
Innophi SlimerJS 0.10.0, Copyright 2012-2016 Laurent Jouanneau & Innophi
```

Running on Oracle Linux 6. Haven't tested any other platforms, yet.

I wasn't using slimerjs master (installed from release zip), although I was using casperjs master.

I just did: 
```
cd /root/
git clone git clone https://github.com/laurentj/slimerjs.git
ln -sf /root/slimerjs/src /usr/bin/slimerjs
```
and the selftest still passes (with the exception of a logging.js failure)

Curious, though, the slimerjs version isn't at 0.10.0:
```
slimerjs --version
Innophi SlimerJS 1.0.0-pre, Copyright 2012-2016 Laurent Jouanneau & Innophi
```
I just tested re-installing casperjs from master using git. I used `https://github.com/casperjs/casperjs/tarball/master` previously:
```
cd /root/
git clone git clone https://github.com/casperjs/casperjs.git
ln -sf /root/casperjs/bin/casperjs /usr/bin/casperjs
```

Could it be that I already phantomjs installed and this isn't a "clean" system so-to-speak? Casper using phantom at some point until it finds out the --engine is overridden?

**Comment by mlalpho** [comment] 2016-06-13 11:57
@Huulivoide can you verify if this problem exists if you install phantomjs alongside slimerjs and casperjs? Obviously would be a problem if it's so dependent on phantom that you can't use slimerjs without it...kind of defeats the purpose of swapping engines ;)

**Comment by istr** [comment] 2016-06-29 19:17
@mlalpho good catch... I will try to look into that.

**Comment by Norbotwastaken** [comment] 2016-07-05 20:42
@mlalpho I can no longer reproduce this issue on OS X. Attempted with both installed slimerJS 0.10 and the current git source, with or without phantomJS installed.

**Comment by kensoh** [comment] 2017-05-20 15:16
@Huulivoide looks like this issue is fixed? I've been using CasperJS with SlimerJS without issues on macOS, Windows and Linux CentOS. Now using 1.1.4 and 0.10.3. Previously 1.1.3 and 0.10.2 also works for me.

**Comment by kensoh** [comment] 2017-05-23 16:19
Looks like this issue has been fixed. Was browsing through the open issues and didn't see any other occurrence of this. Closing this for now but kindly ping here or ken@tebel.org if you have any inputs!

**Closed by kensoh** 2017-05-23 16:19 UTC
Labels: Needs Investigation, SlimerJS
