### ISSUE TITLE
Casperjs --xunit not working properly

### ISSUE THREAD

**Issue by nagoleon** [casperjs/casperjs#1542] opened 2016-04-19 12:37 UTC
Hello,

Using both the released version (tar.gz) for 1.1.0 and the latest git clone in cunjunction with phantomjs 2.0.0 (gentoo amd64), i'm unable to produce any result using the xunit flag i was able to reproduce with a very simple:

casperjs selftest --xunit=log.xml

Which should run all tests from casperjs internal test suite and then report the result in the log.xml file created in the current dir. The file is created but it contains the following:

<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE casperjs PUBLIC "-//CasperJS//XUnit Test Results" "testsuites"><testsuites/>

I can also reproduce in my own testsuite but i thought this was a good way for developers to test this issue.

**Comment by BIGjuevos** [comment] 2016-04-19 14:06
Thanks for reporting; however, this is a duplicate of #1535.

Closing as we already have a fix in the works.  We plan to have a fix out soon.

**Closed by BIGjuevos** 2016-04-19 14:06 UTC

**Comment by nagoleon** [comment] 2016-04-19 16:11
Hello and thanks for the quick reply, nice to see casperjs get out of its slump, it's a very nice tool to have on top of phantomjs.

I was aware of #1535 but since it's tagged as a phantomjs 1.9 issue which it is not, i think the issue should be clarified as non dependant on phantomjs version, also since it affects a feature on a released version in a regressive way it probably deserves a "critical" status of some sort.

**Comment by BIGjuevos** [comment] 2016-04-19 16:15
Good point, I've updated the other issue to represent that it is affecting all versions of phantomjs.

**Comment by nagoleon** [comment] 2016-04-19 17:28
Well, it's in fact affecting casperjs the current state in git and the released version (1.1.0) more than being related to phantomjs if we want to be exact.
