### ISSUE TITLE
casper each batch open

### ISSUE THREAD

**Issue by brucejcw** [casperjs/casperjs#1545] opened 2016-04-20 07:19 UTC
```
casper.start().each views, (self, view) ->
    self.echo view.name +1
    self.open(view.url).then ()->
        this.wait(2000)
        this.echo view.name + 2
```

The console log shows all `view.name + 1` immediately, but output `view.name +2` one by one,  each through 2s, so the total time will be **view.length *2** , I guess it is because the `then` which after `open`  
Can casper async open all at the same time when I use `each`? So the total time can be around 2s  
Thanks

**Comment by Awakening-j** [comment] 2016-04-27 08:08
+1

**Comment by kensoh** [comment] 2017-05-23 23:21
@brucejcw this looks like by design. I understand that then is meant to make execution synchronous instead of async. Bumping this up.

**Comment by kensoh** [comment] 2017-06-02 04:17
Hi @brucejcw closing this for now but please reopen if you still have question on this. Thanks for raising this!

**Closed by kensoh** 2017-06-02 04:17 UTC
Labels: Help Request
