### ISSUE TITLE
evaluate function argument changes from JSON to String unexpectedly 

### ISSUE THREAD

**Issue by robin-obrien** [casperjs/casperjs#1471] opened 2016-03-05 21:42 UTC
I have an App that includes the following code:

```
...
console.log("Location1:"+JSON.stringify(location));
casper.evaluate(function parseLocation(location) {
   console.log("Location2:"+JSON.stringify(location));
}, location);
...
```

When I run it, I get the following logs:
Location1:{"coordinates":"42.7,25.30"}
[debug] [phantom] Location2:"42.7,25.30"

Why does the type change?

**Comment by desmond276** [comment] 2016-03-24 23:15
I looked into this.  The type changes here when utils.objectValues is called  (this is the casper.prototype.evaluate func):

` else if (arguments.length === 2) {
        // check for closure signature if it matches context
        if (utils.isObject(context) && eval(fn).length === Object.keys(context).length) {
            context = utils.objectValues(context);
        } else {
            context = [context];
        }
    }`


Looks like utils.objectValues changes an object into an array.  Consequently, it strips the key off the object.  I'm not sure why casper does that for only objects with length of 1.  

I would like to contribute some fix but I'm afraid that I might change something that was intended for something else.   (trying to get into open source =))

**Comment by BIGjuevos** [comment] 2016-03-24 23:47
@desmond276 Please put in a pull request.  We're all here to help out, and your pull request would be checked.  We also have lots of tests to ensure we don't break things.

**Comment by istr** [comment] 2016-03-29 10:42
@desmond276 Yes, if you have a fix in mind, just create a PR. It will be reviewed and merged after discussion if appropriate.

**Comment by kensoh** [comment] 2017-05-23 23:47
Thanks @robin-obrien for raising this and maybe @desmond276 could relook on a PR if you can? :)

**Comment by kensoh** [comment] 2017-08-18 00:56
Closing this issue for now as there hasn't been progress and a PR may not be likely. But do reopen if anything!

**Closed by kensoh** 2017-08-18 00:56 UTC
Labels: Help Request, Needs Investigation
