### ISSUE TITLE
TypeError: Attempting to change the setter of an unconfigurable property.

### ISSUE THREAD

**Issue by ISKU** [casperjs/casperjs#1935] opened 2018-05-26 11:02 UTC
Hi :D

I have encountered errors since upgrading the Ubuntu 18.04 LTS.
My program works as follows.
Use the casper.echo() method to output messages to the console
Then the child-process reads the message from the console.

``` javascripts
casper.echo(JSON.stringify(table, null, 4), function() {
    casper.exit();
});
```
``` javascripts
spawn.stdout.on('data', function(data) {
    JSON.parse(data);
});
```

The buffer(data) contains the following error and it can not be parsed.
An error occurs as follows:
```
<Buffer 54 79 70 65 45 72 72 6f 72 3a 20 41 74 74 65 6d 70 74 69 6e 67 20 74 6f 20 63 68 61 6e 67 65 20 74 68 65 20 73 65 74 74 65 72 20 6f 66 20 61 6e 20 75 ... >
TypeError: Attempting to change the setter of an unconfigurable property.
```

It works fine in ubuntu 17.10.
Could this be a problem with CasperJS? Or is there a PhantomJS error or is there any other reason?
can you help? please.

Versions
- CasperJS: 1.1.4
- PhantomJS: 2.1.1
- NodeJS: v8.10.0
- OS: Ubuntu 18.04 LTS

Thanks.

**Comment by kanwar-saad** [comment] 2018-06-06 11:56
same here. I tried a demo program with phantomJS only and saw the same error there. so it is coming from phantomJS.

**Comment by ISKU** [comment] 2018-06-09 12:58
I don't want this error to be output to the console.

![image](https://user-images.githubusercontent.com/14817203/41191819-11bbb92a-6c30-11e8-80f6-6606543306cb.png)

**Comment by kensoh** [comment] 2018-06-11 15:12
Yes @kanwar-saad confirmed to be issue upstream at PJS.

@ISKU this is the PJS issue - https://github.com/ariya/phantomjs/issues/15360

**Comment by jhare** [comment] 2018-06-26 17:59
Also experiencing, staying tuned. This is annoying in my case because my casper program streams JSON output to its parent, this really throws a monkey wrench in all that. What garbage.

**Comment by kensoh** [comment] 2018-06-27 10:19
Is it possible to filter that extra text away from bash or the wrapper that invokes CasperJS? Since this issue happens upstream in PhantomJS it can't be fixed within CasperJS.

**Comment by jhare** [comment] 2018-06-27 11:28
@kensoh For sure. I adjusted invocation of my program and was able to work around and add some flags. Not a show stopper and not Casper's fault. My anger remains generally directed at PJS.

**Comment by kanwar-saad** [comment] 2018-06-27 11:52
@jhare PJS is suspended for the time being so I don't think anyone will fix this issue soon.

**Comment by kensoh** [comment] 2018-06-27 11:55
I see.. Gotcha, thanks for sharing that you did a workaround. Yeah PJS is suspended (https://github.com/ariya/phantomjs/issues/15344) --> I hope that its community will at least continue to cut releases for future OSes.

**Comment by ISKU** [comment] 2018-06-27 22:54
@kanwar-saad @jhare @kensoh  Thanks. 
I can not service my program. Is there no way to bypass this error in CasperJS?
Maybe I'll have to modify my program in a different way.
Or, rather than wait for this error to be fixed, I plan to create a new program that does not use CasperJS.

**Comment by kensoh** [comment] 2018-07-26 00:53
Closing this for now as CasperJS, similar to PhantomJS is not actively maintained.

**Closed by kensoh** 2018-07-26 00:53 UTC
