### ISSUE TITLE
Code example for scraping throwing error

### ISSUE THREAD

**Issue by arimourao** [casperjs/casperjs#1866] opened 2017-08-06 01:54 UTC
I just started testing casperjs together with phantomjs and it seems great. But your own example code is throwing an error right off the bat.
In the section "Scraping" the following code is shown:
```
var casper = require('casper').create();
var links;

function getLinks() {
// Scrape the links from top-right nav of the website
    var links = document.querySelectorAll('ul.navigation li a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href')
    });
}

// Opens casperjs homepage
casper.start('http://casperjs.org/');

casper.then(function () {
    links = this.evaluate(getLinks);
});

casper.run(function () {
    for(var i in links) {
        console.log(links[i]);
    }
    casper.done();
});
```

The following error is shown in the shell:

```TypeError: undefined is not a function (evaluating 'casper.done()')  ```

Since I just started playing with the API, I couldn't find a way to fix this other than commenting the casper.done() section, but that leaves the script still running.

My node version is 8.2.1 running on Debian Jessie.

**Comment by kensoh** [comment] 2017-08-06 14:00
Hi @arimourao thanks for feedback! Can you try with below block of code? The [.done method](http://docs.casperjs.org/en/latest/modules/tester.html#done) I believe is now used when running in test mode so maybe that is the cause of the issue. I can replicate the error with the code above. The quick start needs to be updated.

Also copying @jefleponot who is maintaining CasperJS now. I'm a user for couple of years, so sometimes I look around to help out on issues that I can help with.

```js
var casper = require('casper').create();
var links;

function getLinks() {
// Scrape the links from top-right nav of the website
    var links = document.querySelectorAll('ul.navigation li a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href')
    });
}

// Opens casperjs homepage
casper.start('http://casperjs.org/');

casper.then(function () {
    links = this.evaluate(getLinks);
});

casper.then(function () {
    for(var i in links) {
        console.log(links[i]);
    }
});

casper.run();
```

**Comment by kensoh** [comment] 2017-08-06 14:03
Are you using CasperJS specifically for scraping? I thought Python-based tools are great for that, eg Scrapy or PYSpider. They may not render the DOM data that is JS based though, I'm not sure.

**Comment by arimourao** [comment] 2017-08-06 17:28
Hi @kensoh your code works alright, tnx. Yes I'm using CasperJS now for scraping a wallpaper website, just a hobby project to learn more about casper/phamtomjs and then use it in more serious projects to automate interface testing.

**Comment by kensoh** [comment] 2017-08-06 17:39
Welcome @arimourao I see.. Interacting with websites using code can be very interesting, have fun!

**Comment by jefleponot** [comment] 2017-08-21 12:57
@arimourao 
Plesae close the issue

**Comment by kensoh** [comment] 2017-08-22 03:17
Let me see if I can put in a PR to update this in docs. As the outdated doc using casper.done() will throw errors.

**Comment by kensoh** [comment] 2017-08-22 04:25
Hi @jefleponot I looked at the documentation and the [quickstart.rst](http://docs.casperjs.org/en/latest/quickstart.html) looks ok and not using casper.done() inside casper.run(). But the CasperJS homepage http://casperjs.org is outdated. Do you know who has access to casperjs.org to update the example?

The homepage doesn't look like part of CasperJS repo, can't find anything when searched for '// Opens casperjs homepage'. For the scraping example to work, it can be modified to the following - 

```js
var casper = require('casper').create();
var links;

function getLinks() {
// Scrape the links from top-right nav of the website
    var links = document.querySelectorAll('ul.navigation li a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href')
    });
}

// Opens casperjs homepage
casper.start('http://casperjs.org/');

casper.then(function () {
    links = this.evaluate(getLinks);
    for(var i in links) {
        console.log(links[i]);
    }
});

casper.run();
```

**Comment by kensoh** [comment] 2017-08-24 03:05
(also cc Ryan @BIGjuevos who created the new casperjs.org site as he may have access to update)

**Comment by kensoh** [comment] 2018-02-19 07:13
Copying @jefleponot and @BIGjuevos again on documentation update for casperjs.org website.

**Comment by kensoh** [comment] 2018-03-16 01:20
Bumping -

**Comment by zhangjh** [comment] 2018-05-27 05:42
@kensoh Your code remove the code:
```
casper.done();
```
then it doesn't finish after console the links.
Maybe the right code is change `casper.done()` to `casper.exit()`

```
var casper = require('casper').create();
var links;

function getLinks() {
// Scrape the links from top-right nav of the website
    var links = document.querySelectorAll('ul.navigation li a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href')
    });
}

// Opens casperjs homepage
casper.start('http://casperjs.org/');

casper.then(function () {
    links = this.evaluate(getLinks);
});

casper.run(function () {
	for(var i in links) {
        console.log(links[i]);
    }
	this.exit();
});
```

**Comment by kensoh** [comment] 2018-05-27 06:40
Thanks @zhangjh for sharing your findings -

I don't think casper.done() is a standard method used anymore - http://docs.casperjs.org/en/latest/modules/casper.html#casper-prototype

I used test.done() for running in test mode though - http://docs.casperjs.org/en/latest/modules/tester.html#done

**Comment by zhangjh** [comment] 2018-05-27 12:36
Yes. What I mean and this issue means: the example code in docs is wrong. 
![image](https://user-images.githubusercontent.com/3371714/40585994-6c793146-61ed-11e8-885b-67ecbeabe4c7.png)

It should use `casper.exit()` to replace `casper.done()`

**Comment by kensoh** [comment] 2018-05-27 12:43
Yes, the documentation is wrong, I'll write the script this way instead - https://github.com/casperjs/casperjs/issues/1866#issuecomment-323915766

But I don't have access to casperjs.org website to make changes there, not sure who has. Been bumping the thread to no success 🤣

**Comment by zhangjh** [comment] 2018-05-27 12:55
@kensoh 
emm....Maybe my poor english couldn't express myself clearly, I mean your code "[#1866(comment)](https://github.com/casperjs/casperjs/issues/1866#issuecomment-323915766)" is also wrong, it will hang after task finished.

**Comment by kensoh** [comment] 2018-05-27 13:40
Oh your English is good, I am not sure why, but the script works for me -

```js
TA:Desktop kensoh$ cat sample.js
var casper = require('casper').create();
var links;

function getLinks() {
// Scrape the links from top-right nav of the website
    var links = document.querySelectorAll('ul.navigation li a');
    return Array.prototype.map.call(links, function (e) {
        return e.getAttribute('href')
    });
}

// Opens casperjs homepage
casper.start('http://casperjs.org/');

casper.then(function () {
    links = this.evaluate(getLinks);
    for(var i in links) {
        console.log(links[i]);
    }
});

casper.run();
```
```
TA:Desktop kensoh$ casperjs --version
1.1.4
TA:Desktop kensoh$ casperjs sample.js
http://docs.casperjs.org/en/latest/quickstart.html
http://docs.casperjs.org/en/latest/
https://github.com/casperjs/casperjs
https://groups.google.com/forum/#!forum/casperjs
```

**Comment by kensoh** [comment] 2018-07-26 03:32
Closing the issue as CasperJS, like PhantomJS, is not being actively maintained. But do continue discussion if any!

**Closed by kensoh** 2018-07-26 03:32 UTC
Labels: Documentation
