### ISSUE TITLE
2.0 Scope and Discussion

### ISSUE THREAD

**Issue by BIGjuevos** [casperjs/casperjs#1524] opened 2016-04-12 15:58 UTC
Mainly for @istr and @mickaelandrieu.

If we are targeting features and things for 2.0, what is the status of the 2.0 branch?
Do we just need to re-sync with master?
Should it be re-created?

**Comment by BIGjuevos** [comment] 2016-04-14 21:39
Based on the discussions I've seen arising, I want to try and consolidate what we are going to shoot for with the 2.0 release:

I'm going to start consolidating a vision for 2.0, So I want to get contributor and community feedback on the following things.

I want to hear what everyone has to think on the following things.

1. Testing
 1. Pull out completely
 2. Extract into driver based
 3. What testing engines to support?
2. Node Support
 1. Make completely node
 2. Screw node
3. Interface
 1. Any backwards compatibility?
 2. Screw backwards compatibility!
4. Branch
 1. Keep around
 2. Kill and start over
5. Code carry-over
 1. Keep it and re-work it
 2. Start from scratch and pull over only what we need.
6. Feature bloat
 1. Will we port all features
 2. We kill some features
7. PhantomJS
 1. Only support 2.0+
 2. Keep 1.9.x support.
8. SlimerJS
 1. Support what versions?
 2. Is engine agnosticism possible?
9. Other engines
 1. Can we support any other engines?

**Comment by paazmaya** [comment] 2016-04-15 07:27
2. Completely Node, would help in the suggestion below on ChacraCore
7. Only PhantomJS 2.0, hence reducing support effort
8. Take`0.10.0`, according to a recent commit https://github.com/laurentj/slimerjs/commit/088d7185dfc19e0f05b3f47260bba771ef101e89
9. #688 TrifleJS, but then again would be interesting to see how ChacraCore car be utilized...

**Comment by BIGjuevos** [comment] 2016-04-15 15:23
@paazmaya is there a decent ChakraCore headless browser out there yet that is cross platform?

All I found was JS emulators, no rendering.

**Comment by mickaelandrieu** [comment] 2016-04-15 15:31
@BIGjuevos we should try to plan a meeting on slack/gitter/hangout with all the active contributors, I'm pretty sure we can found help and skilled people to help us bootstrap and maintain both CasperJS 1.x et 2.x (if CasperJS 2 is fully compatible with node, it's 100% sure :p )

**Comment by BIGjuevos** [comment] 2016-04-15 16:47
I like the concept of a google hangout. Problem is I am west coast US and I'm pretty sure you are all GMT +/- 2 hours. 

I've got istr on LinkedIn already for coordination. Can you add me as well, and anyone else who wants in on the meeting and I'll get a time figured out.

**Comment by hexid** [comment] 2016-04-15 18:56
1)  With a switch to Node, we could use a testing framework such as Mocha

2)  I'm all for making the switch to Node

7)  If it is decided to drop support for PhantomJS 1.x, then there are a lot of workarounds that will no longer be necessary. Dropping support here may affect 5.

It may also be a good idea to remove the dependency on Python if we decide to move to Node. We would also be able to unify the launchers (no more compiling Windows binaries :+1:)

**Comment by istr** [comment] 2016-04-18 11:29
WRT driving PhantomJS using nodejs, see https://github.com/johntitus/node-horseman

**Comment by istr** [comment] 2016-04-18 11:53
Another useful starting point might be this simple engine -> nodejs bridge:
https://github.com/baudehlo/node-phantom-simple

**Comment by istr** [comment] 2016-04-18 12:05
> It may also be a good idea to remove the dependency on Python

That would be a very good idea -- mainly because you need a full-fledged python setup now, ```python-minimal``` only is not sufficient.

**Comment by mickaelandrieu** [comment] 2016-04-18 12:31
> Another useful starting point might be this simple engine -> nodejs bridge: https://github.com/baudehlo/node-phantom-simple

Thanks for the link, I realy need to look at it since I have now some basics in node :D (when I started to contribute to CasperJS, I was a ashamed PHP developer only, "booh")

**Comment by nagoleon** [comment] 2016-04-19 17:48
1- Testing is the main feature i don't see why this would be dropped or my non-native english skills make me understand this wrong. Test is fine in the current state, i understand why this would become a driver tho, it's probably a good code compartimentalizing thing to do
2- Node is a good feature to have, but it's far from being the only domain where casperjs can be of serious use, it's a very good web api testing framework, it's a very good javascript framework testing framework, not just for node, so i would reply don't screw node, but don't screw what is not node either
3- screw backward compatibility it can always be achieved after the fact if the project is carefully thought.
4- There should only be two branches 1.0 for phantom 1.9 support, which is a request that some may have, also the documentation for this may be hard to find (i struggled once to find it) the other branch should be 1.1 and above (1.1 should disapear in favor of 2.0 when release assuming they are equal in features)
5- Start from scratch and pull over only what we need. It's way harder to re-arrange code than creating new one, the result will always be better, and actually i'v done that quite a few time in my career and this will be faster to complete too.
6- Keeping features is a must, because the variety of actual users surely use a lot of it.
7- phantomjs on some linuces can hardly be upgraded above 1.9 but this will happen sooner or later, last i checked in november ubuntu couldn't have phantomjs 2.0 because there was a need to compile it which is not the ubuntu way, so i guess debian is the same. That been said i don't think it's worth maintaining compatibility with 1.9 because there is always casperjs 1.0 that is good to go with it.
8- Never tester SlimmerJS yet, i cannot say much here.
9- If there was a way to support IE/Edge based that would be usefull but at a low low low priority given that Chrome + Mozilla have like 80% shares in the browser world (well actually chrome alone...isn't that far)

That's my 2cts

**Comment by mickaelandrieu** [comment] 2016-04-19 21:07
@nagoleon CasperJS is and was intended to be a wrapper of PhantomJS :)  It becomes a testing framework only cause @n1k0 have time to waste during a train trip :p  There are a lot of better testing frameworks,  we just need to make CasperJS better to allow something like Chai and Mocha for instance.

**Comment by nagoleon** [comment] 2016-04-19 21:47
@mickaelandrieu chai and mocha depend on node.js so i disagree no there is nothing better than casperjs doing what it does about the testing. I don't understand why it would depend on node.js at all by the way i understand why node.js needs unit testing, i don't understand why anything else would require it.

In january i have been testing a lot of solutions for the company i worked for at the time for testing a php/js environment so i ended up discovering casperjs which i found very good but posed one big issue with the lack of phantomjs 2.0 support, a few days ago i was ready to start unit testing on my project and i had in mind to just develop something with phantomjs 2.0 that would end up being comparable to casper in its functionalities, and then i found out that there was a revival and that indeed there was a casperjs version that actually worked for phantomjs 2.0. So here i am, but reading this topic actually got me scared, being without testing framework, or constrained to a node.js environment would definely be a no go and i'd have to just develop something else, i'm not sure i'm representative of anything but just so you know how i ended up here.

**Comment by BIGjuevos** [comment] 2016-04-19 22:14
At this point we are not ruling out a testing framework.  The desire from the team is not that it be **core** functionality.

There's no objection to having it be a "plugin" or extended functionality.  If you wanted to adopt this functionality if we move forward with the plan we're thinking of, I think that'd be wonderful!

**Comment by hexid** [comment] 2016-04-19 22:25
It was my understanding that it is mostly the Python code that would be ported over to run on Node.

If this is correct, it shouldn't have much impact on users, but instead allow us to write the wrapper and internal tests in Javascript instead of Python/C#.

**Comment by n1k0** [comment] 2016-04-20 04:43
>  chai and mocha depend on node.js

Not really, they're perfectly useable from a browser page for example. In a past life I've been running mocha test scripts from Selenium :)

As @BIGjuevos said, what I had in mind wasn't to kill the casperjs native testing framework, but rather to make it an optional dependency not being part of the core anymore, so people wanting to use something else could do so much more easily. That's a bunch of work though as AFAICR there are many bits of the testing framework invoked right from the core atm, which is pretty bad from an architectural perspective.

**Comment by nathanboktae** [comment] 2016-04-22 16:06
> chai and mocha depend on node.js

Not at all. I've been supporting them in casperjs [for 3 years now.](https://github.com/nathanboktae/mocha-casperjs)

Node vs not node is not that interesting of a discussion (for the core product, for what you guys use to test Casper, sure). The biggest draw for casperjs is running inside the same process as your browser and not having to deal with the IPC / network calls, latency, and delay that is a pain in Selenium. The bootstrappers can just be shell scripts.

> The desire from the team is not that it be core functionality.

Yes I agree, let people bring their own frameworks & assertion libraries for this.

**Comment by BIGjuevos** [comment] 2016-04-22 18:19
So, to gather the consensus so far:
1. Start the codebase over, and pull in what we need from the v1.x codebase.
2. Node, node, node.
3. Testing capabilities are to be yanked out and to be replaced with an interface that pairs nicely with more established testing frameworks.
4. Look into supporting an IE headless
5. Only support phantomjs 2.x and up.
6. Casper 1.x will become LTS and exist for legacy use.

So, in order to start making some ground on this, I'll draft up some API and design docs and post them here based on the discussions here and my review of the project history.  Bear with me, might take a few weeks.  In the meantime, please continue to discuss!

**Comment by nagoleon** [comment] 2016-04-22 18:33
There seems to be a misunderstanding about what i said earlier, when i said depending on Node.js i wasn't meaning the interface, i mean depending on the installation of Node.js as a pre-requisite framework kind of thing, this, to me, doesn't make any sense and void the biggest selling point of casperjs, the only dependency should be phantomjs, slimmer or an IE based similar product, of you add up Node.js in the mix well, chances are casperjs will be another node.js tool and there are others right now, while non node.js dependant tools are rare or non-existent right now.

**Comment by BIGjuevos** [comment] 2016-04-22 18:46
@nagoleon 
>  i mean depending on the installation of Node.js as a pre-requisite framework kind of thing
Everyplace I've worked or done things for uses node, if you are doing things that involve this kind of testing, the likelihood is that node is there as well.

> non node.js dependant tools are rare or non-existent right now
How common is the use case that people are developing in JS and aren't utilizing node?  I think your statement is a testament to the state of the industry as it stands now.  Node.js has become an ubiquitous tool for many good reasons.

>  add up Node.js in the mix well
Is there a reason we can't support runners in windows, linux, and node?

**Comment by nagoleon** [comment] 2016-04-22 19:05
If you are a Node.js developer i don't doubt that every place where you worked uses Node. But thinking Node is even a common technology is utterly crazy... With PHP Java, Ruby and Python well above it on the market share Node.js is a rarity in fact.

http://w3techs.com/technologies/details/ws-nodejs/all/all

That's 0.2% of the worl website so.. need i say more about why this is a very wrong idea to depend on it?

**Comment by BIGjuevos** [comment] 2016-04-22 19:22
I concur with your premise of low node production server usage.  However, Node is ubiquitous when it comes to tooling and behind the scenes operations.  Which in my opinion is that largest segment of the CasperJS (and other build-time tools) user base.

If you are using node and the tooling it offers on the backend to build your JS for production usage, then the likelihood is that you soon will. See: https://nodesource.com/blog/enterprise-node-js-adoption-increases/

See the latest SO Developer Survey: http://stackoverflow.com/research/developer-survey-2016#most-popular-technologies-per-occupation

It shows JS as most popular language and Node at 27-32% usage for ttop/backend/full stack for application.  I think that this is a market worth servicing.

Moreover, node provides a built in community of adopters and contributors that want to improve the ecosystem in which they exist.  That is beneficial for the health of the CasperJS community itself.

Finally, not ruling out not supporting other runners.  There is just a high interest in adding node support.

**Comment by nagoleon** [comment] 2016-04-22 19:35
I don't understand why the argument is "using node to build", node is a technology that is hybrid between a framework and a language right? but javascript is the language, and javascript for the users is developed on the client side, because well... no user care how you connect your database it's a developer thing. Developer choose that because they like it because it offers the features they like and so on. If we can agree on all that then, my point is that casperjs is a tool that allows developers to develop javascript for users (hence on the client side) assuming that's still right ... why in world would we limit that to the people that uses and like node when the actual version can work for those and for the others? More is better is it not?

**Comment by istr** [comment] 2016-04-23 09:59
WRT "all node" / "add node bridge":

I would definitely stick with "keep it standalone / self-contained" and try to provide a nodejs bridge as a "non-core" add-on, while keeping the CasperJS npm packaging. Rationale:
- lots of comments and users indicate that they feel it is a desirable feature of CasperJS to be self-contained (just to name two: #462, #1342), this includes myself
- many users seem to use npm and regularly install CasperJS through npm as a convenience
- the demand for a bridge to run node -> CasperJS -> PhantomJS directly is 	durable and high, like @n1k0 pointed out

While working with a "nodejs based frontend tooling" myself I find it a major PITA more often than not, but rather due to the broken dependency model of npm [aka dependency hell](https://github.com/casperjs/casperjs/issues/1342#issuecomment-208797171) it introduces and the need to rely on a 3rd party registry it fosters -- not due to the need to use nodejs itself.

**Comment by mlalpho** [comment] 2016-06-11 14:46
chiming in here.. As a full-stack developer in a node-less environment, having casperjs NOT rely on node and all it entails is a HUGE WIN. Put me down for the node-bridge and keeping the Tester module as a non-core plugin that can still be used. 

Feel free to switch to mocha/chai/latte(joke) whatever in your dev environment, but, don't force everyone to use Node just because you like it. 

I'd be open to allowing folks to choose the testing/assertion lib that casperjs calls like --test-engine=casper or --test-engine=mocha etc.. In my opinion that would only make CasperJS 10x more appealing.

Supporting npm and getting the Node community involved is definitely a win.. but, you also don't want to alienate the other 80% of the world that's not using Node. 

My $0.02

**Comment by orensol** [comment] 2016-07-26 11:02
+1 for keeping self contained, but providing a fully supported node bridge.

**Comment by kensoh** [comment] 2017-05-20 15:50
Second @istr @mlalpho @orensol on no dependency on node. I personally prefer the lesser dependencies the better so if it can run without being inside node it's a good thing. I only use the npm ecosystem for easier packaging and distribution. But non-node users should still be able to enjoy benefits of CasperJS without strictly being made to migrate to a node env.

**Comment by kensoh** [comment] 2017-08-18 00:43
Referencing https://github.com/casperjs/casperjs/issues/1825 -  Develop Casper JS to work with new headless Chrome to replace Phantomjs

As it is probably a topic for discussion in this thread towards CasperJS v2.0

**Comment by kensoh** [comment] 2018-03-16 01:07
Nope, also copying maintainer @jefleponot -

CasperJS is built on PhantomJS. It is inherently not compatible with Chrome-based automation as the JS version is different. However, to pluck out PJS and implement a new branch for Chrome is a mammoth task which probably takes full-time paid job to do it.

If you really really need Chrome automation but with CasperJS, try this framework I made. It basically generates CasperJS scripts but at the same time can automate Chrome directly through WebSocket connection.

http://github.com/tebelorg/TagUI

It only implements a subset of key CasperJS methods for Chrome, so it isn't possible to merge upstream here. Both due to lack of full API, and technical incompatibility. Execution environment is still PJS but I make calls to Chrome to drive its automation.

**Comment by nathanboktae** [comment] 2018-03-16 06:24
> which probably takes full-time paid job to do it.

Given phantomjs is [being archived and no longer maintained](https://github.com/ariya/phantomjs/issues/15344) and the competitor these days to casperjs is [Nighmare.js](https://github.com/segmentio/nightmare) on [electron](https://github.com/electron/electron), which are maintained by [Segment.io](https://www.crunchbase.com/organization/segment-io) and Github respectively, two very profiltable companies that likely do have people who's full time job is to maintain them, we should all move on to those projects. Thanks to @n1k0  and all the maintainers of casperjs over the years, it was great.

**Comment by kensoh** [comment] 2018-03-16 09:51
Oops I'm sorry, I meant to post at the other thread to a user question - https://github.com/casperjs/casperjs/issues/1825

**Comment by kensoh** [comment] 2018-07-26 03:49
Archiving issue using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now.

**Closed by kensoh** 2018-07-26 03:49 UTC
Labels: ARCHIVE, General Discussion
