### ISSUE TITLE
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by jpca999** [casperjs/casperjs#1792] opened 2017-03-19 17:48 UTC
whenver i try to load undersocre it spits this error. 

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.

casper.then(function(){

    var objects = [{ 'a': 1 }, { 'a': 2 }];
    var grab = _.map(objects, 'a');

**Comment by jefleponot** [comment] 2017-03-20 09:36
@jpca999 

Could you precise CasperJs version / PhantomJS or SLimerJS + version ?

Any Example ?

**Comment by jpca999** [comment] 2017-03-21 20:19
![2__jay_jai____dropbox_life_changing_mentoring_program_code_excel-to-json-conversion__zsh_](https://cloud.githubusercontent.com/assets/1026325/24168862/176d4d80-0e52-11e7-9994-b2dff6e9f351.jpg)

**Comment by jefleponot** [comment] 2017-03-22 06:08
@jpca999 
I have no idea !! How could we reproduce the bug ?

**Comment by kensoh** [comment] 2017-05-20 14:47
Hi @jpca999 I'm an CasperJS user but haven't come across the use of _ directly as a variable. Not sure if it is because the underlying tech (PhantomJS/SlimerJS) is not supporting ES6/TypeScript in below link. And whether what you want to achieve can be done without using _

http://stackoverflow.com/questions/41085189/using-underscore-variable-with-arrow-functions-in-es6-typescript

**Comment by kensoh** [comment] 2017-05-20 14:54
Cross-referenced above duplicated issue. Looks like you are trying to use Lodash with CasperJS.

I'm not JavaScript expert, so maybe Jef or other Lodash expert can share with info with you.

**Comment by kensoh** [comment] 2017-06-05 03:04
@jpca999 closing the issue but do reopen if it is still a concern to you and there is something we can assist on! It looks like a Lodash-CasperJS specific conflict or issue.

**Closed by kensoh** 2017-06-05 03:04 UTC
