### ISSUE TITLE
Can't click button

### ISSUE THREAD

**Issue by O0mix0O** [casperjs/casperjs#1552] opened 2016-04-22 14:28 UTC
Hi all,

It may sound like I'm a fool/ this is an easy answer but I've tried multiple methods of clicking the button at the end of the form, with no joy.
I've been able to click other buttons whilst filling the form but this one won't work.
I've tried:
- clicklabel()
- click()
-  Selecting via XPath
- Selecting via CSS
- Waiting (to see if it's the page loading slowly)

The code below enters a car reg number, clicks the button, and then submits the form. Currently, the car button is clicked, but the form button isn't. 
If the form submission _was_ successful, the screenshot should show multiple error messages. (If the required info _is_ entered, the form should load the next page).

If the rest of the code is required, please say :)

```
var x = require('casper').selectXPath;
var casper = require('casper').create({
    verbose: false,
    logLevel: "debug"
});

//Open site and ensure it has loaded:
casper.start('https://www.moneysupermarket.com/shop/car-insurance/questionset/#?step=highimpactquestions');
casper.waitForSelector('h2.msm-title.title-lg-left.title-md-left.title-xs-center', function() {
    if (this.exists('h2.msm-title.title-lg-left.title-md-left.title-xs-center')) {
        this.echo('Loaded patients');
    } else {
        this.echo('Couldnt load page');
    }
});

//Enter registration number
casper.then(function() {
    this.echo('Entering - Registration number');
    if (this.exists('input#regnumber')) {
        this.sendKeys('input#regnumber', regNumber);
        this.echo('Entered - Registration number');
    } else {
        this.echo('Couldnt enter - Registration number');
    }
});

//Click find car button
casper.then(function() {
    this.echo('Clicking - Find car button');
    if (this.exists(x('//*[@id="regnumber"]/div[2]/button'))) {
        this.click(x('//*[@id="regnumber"]/div[2]/button'));
        this.echo('Clicked - Find car button');
    } else {
        this.echo('Couldnt click - Find car button');
    }
});

casper.then(function() {
    this.echo('Clicking - Next button');
    if (this.exists(x('//*[@id="questionHolder"]/div[5]/div[2]/button[1]'))) {

        this.click(x('//*[@id="questionHolder"]/div[5]/div[2]/button[1]'));
        this.echo('Clicked - Next button');

        // this.clickLabel(' Continue to step 2 ', 'button');
        // this.echo('Clicked - Next button Label');

    } else {
        this.echo('Couldnt click - Next button');
    }
});

casper.then(function() {
    casper.wait(10000);
    this.capture('moneysupermarket.png')
});
```

**Comment by BIGjuevos** [comment] 2016-04-22 21:10
@O0mix0O What happens if you use CSS selectors instead?

**Comment by O0mix0O** [comment] 2016-04-22 22:30
@BIGjuevos I don't think Casper can locate the button using CSS... (Using the code below) it echos the 'Before' and then exits.

```
casper.then(function() {
    this.echo('Clicking - Next button');
    if (this.exists(x('//*[@id="questionHolder"]/div[5]/div[2]/button[1]'))) {

        this.echo('Before');
        this.click('#questionHolder > div.row.form-group > div.col-xs-12.hidden-sm.hidden-md.hidden-lg  > button.btn.btn-primary.btn-continue.loading');
        this.echo('After');

    } else {
        this.echo('Couldnt click - Next button');
    }
});
```

**Comment by BIGjuevos** [comment] 2016-04-25 05:52
@O0mix0O The CSS selectors seems very dense.  What happens if you add an ID directly to the element and then try and do the this.click on it?

**Comment by BIGjuevos** [comment] 2016-04-25 05:54
It's also worth noting that some older versions of phantomjs can be quirky.  Please try updating to a newer version and let us know is that helps.

**Comment by O0mix0O** [comment] 2016-04-25 10:04
@BIGjuevos Thanks for your response.

I'm afraid I'm not familiar with adding properties to an element, the code I have tried doesn't seem to working. Could you point me in the right direction?
```
casper.then(function() {
    this.echo('Adding ID');
    __utils__.getElementByXPath('//*[@id="questionHolder"]/div[5]/div[1]/button').setAttribute("id", "mybuttonid"); 
    this.echo('Added an ID');
});
```

I am currently using Phantom 2.1.1 and Casper 1.1.1

Thanks

**Comment by jefleponot** [comment] 2016-04-25 10:17
Hi @O0mix0O ,

When you test a selector, it is better to reuse the same selector ;

```js
casper.then(function() {
    this.echo('Clicking - Next button');
    var mySelector  = x('//*[@id="questionHolder"]/div[5]/div[2]/button[1]');
    if (this.exists(mySelector)) {
        this.echo('Before');
        this.click(mySelector);
        this.echo('After');
    } else {
        this.echo('Couldnt click - Next button');
    }
});
```

regards 
jef

**Comment by Dynatrace-BrianWilson** [comment] 2016-12-21 05:21
@jefleponot I just ran into this same issue. For whatever reason, putting the xpath into the variable made it work.  Thanks for posting this.

**Comment by jefleponot** [comment] 2016-12-21 10:00
xpath must be convert into Object.

```js
/**
 * Shortcut to build an XPath selector object.
 *
 * @param  String  expression  The XPath expression
 * @return Object
 * @see    http://casperjs.org/selectors.html
 */
function selectXPath(expression) {
    "use strict";
    return {
        type: 'xpath',
        path: expression,
        toString: function() {
            return this.type + ' selector: ' + this.path;
        }
    };
}
```

**Comment by whooyun** [comment] 2017-04-28 07:08
@O0mix0O

**Comment by kensoh** [comment] 2017-05-20 03:30
Hi @O0mix0O I'm able to replicate this issue and found that the website somehow needs some lag time for the elements to be updated after user action. If I add a casper.wait(2000); between entering each fields and clicking the button it works.

Also, the button due to having no unique ID, using that particular XPath will be invalid after entering some fields. I was able to get the button working by using `//*[@data-ng-class="{loading:buttonSpinner}"])[1]` so you might try that, if you are still interested in this automation after a year.

**Comment by kensoh** [comment] 2017-05-20 03:31
Hi @O0mix0O I'm able to replicate this issue and found that the website somehow needs some lag time for the elements to be updated after user action. If I add a casper.wait(2000); between entering each fields and clicking the button it works.

Also, the button due to having no unique ID, using that particular XPath will be invalid after entering some fields. I was able to get the button working by using `//*[@data-ng-class="{loading:buttonSpinner}"])[1]` so you might try that, if you are still interested in this automation after a year.

**Comment by kensoh** [comment] 2017-05-23 00:28
@O0mix0O it looks like the issue is resolved maybe it's website changed, or adding wait to make sure web events have handled user interaction fixed it. I'll close the issue for now but do ping if you still run into issues. These days I'm on GitHub almost everyday. Otherwise you can email me ken@tebel.org

**Closed by kensoh** 2017-05-23 00:28 UTC
Labels: Help Request

**Comment by O0mix0O** [comment] 2017-05-26 10:20
Hi Ken, and all,

I can only apologise for neglecting this thread and thank you all for your suggestions and contributions. 

Unfortunately, the project this was being used for came to a natural conclusion, however, this information is really useful for any future projects I embark upon as I really enjoyed using Casper!

Thanks again,
Mix

**Comment by kensoh** [comment] 2017-05-26 16:37
No probs Mix! Do ping again if any issues while using CasperJS :smile:

I'm also a fan of CasperJS, using it for various personal laziness.
