### ISSUE TITLE
CasperJS v1.1.3 not working with PhantomJS >1.9.8 on Windows 10

### ISSUE THREAD

**Issue by Nedgeva** [casperjs/casperjs#1673] opened 2016-08-29 18:08 UTC
It's just hangs. Casper prints nothing to console, even simple command 'casperjs --version' gives nothing - no errors or other output. Replacing PhantomJS' executable with lower version (lower than 2.x) resolving issues.

**Comment by BrainyBrian** [comment] 2017-01-04 00:24
I think I am experiencing the same problem on my MacOS Sierra Mac Book Pro

**Comment by Henry-T** [comment] 2017-01-16 11:23
same with me

**Comment by kensoh** [comment] 2017-05-19 23:18
Looks like it might be related to what @entrptaher posted on PhantomJS memory leak?

It actually works for me on Windows 10 and macOS Sierra. Both for CasperJS v1.1.3 and v1.1.4. I'm running PhantomJS v2.1.1. My mac is 4GB, win is 8GB.

**Comment by kensoh** [comment] 2017-05-19 23:19
@Nedgeva @dgramop @Henry-T looks like it might be related to what @entrptaher cross-referenced on PhantomJS memory leak?

It actually works for me on Windows 10 and macOS Sierra. Both for CasperJS v1.1.3 and v1.1.4. I'm running PhantomJS v2.1.1. My mac is 4GB, win is 8GB.

**Comment by kensoh** [comment] 2017-05-25 00:58
Thanks @Nedgeva @dgramop @Henry-T for your inputs above.. Closing this for now but do ping on your steps to reproduce the issue if you are still experiencing the issue with v1.1.4 + v2.1.1.

**Closed by kensoh** 2017-05-25 00:58 UTC
