### ISSUE TITLE
exitOnError(false) doesn't work in 1.1-beta4?

### ISSUE THREAD

**Issue by zzfire** [casperjs/casperjs#1656] opened 2016-07-21 07:06 UTC
sample codes below is trying to wait for a dom which not exist, my purpose is to still can echo "step2" and "done", but always exiting after 5000ms. I install casperjs with brew in mac, version is 1.1-beta4.
Thanks~

```
require('casper').create({exitOnError:false}).start("https://www.baidu.com").then(function(){
  this.waitForSelector('#fafjlafjalfjalfj',function(){
  	this.echo("this dom shouldnot exist, never here");
  });
}).then(function(){
  this.echo("step 2=======");
}).run(function(){
  this.echo("done=================");
  this.exit();
});
```

**Comment by jefleponot** [comment] 2016-07-21 12:23
Hi @zzfire 

you code is not correct

```js
require('casper').create({exitOnError:false}).start("https://www.baidu.com").then(function(){
  this.waitForSelector('#fafjlafjalfjalfj',function(){
    this.echo("this dom shouldnot exist, never here");
  },function(){
    this.echo("this dom don't exist");
  });
}).then(function(){
  this.echo("step 2=======");
}).run(function(){
  this.echo("done=================");
  this.exit();
});
```

exitOnError means that "error" in scripting are ignored but not in running execution.

Regards

**Comment by zzfire** [comment] 2016-07-21 13:23
thanks @jefleponot ,but i still don't understand the difference. "error" in scripting means the plain js error which can be try..catch, and the running execution means the casperjs execution chains?
 despite of the difference, is there any way help me to skip the exiting when wait* family api got timeout?

**Comment by jefleponot** [comment] 2016-07-21 14:33
exitOnError is an error event is triggered  
==> casper.on("error", function(message){ });
or ==> phantom.onError = function(message){};

AND it is not that you need.

-------------
you solve your issue , 2 solutions : 

1.Update the defaut onWaitTimeout method 
```js
onWaitTimeout:       function _onWaitTimeout(timeout) {
            this.die(f("Wait timeout of %dms expired, exiting.", timeout));
        }
```
=> require('casper').create({onWaitTimeout:function(){ console.log("I don't want to die!!!");}});

2.Give another parameter to your waitForSelector method 

=>  

```js
this.waitForSelector('#fafjlafjalfjalfj',function(){
    this.echo("this dom shouldnot exist, never here");
  },function onWaitTimeout(){
    this.echo("this dom don't exist");
  });
```

you are welcome

**Comment by mickaelandrieu** [comment] 2016-07-21 14:48
Hi,

thank you for your answer @jefleponot .

To complete, if you realy need a bigger timeout - let's say 10 seconds you have 2 options:

```js
casper.options.waitTimeout = 10000; // or casper.create({'waitTimeout': 10000})
``` 

or you can use a third argument to [waitForSelector](http://docs.casperjs.org/en/latest/modules/casper.html#waitforselector):

```js
var TIMEOUT = 10000;
this.waitForSelector('#fafjlafjalfjalfj',function(){
    this.echo("this dom shouldnot exist, never here");
  },function onWaitTimeout(){
    this.echo("this dom don't exist");
  }, TIMEOUT);
```

This is definitively not a bug, so I close this issue.

Mickaël

**Closed by mickaelandrieu** 2016-07-21 14:48 UTC

**Comment by zzfire** [comment] 2016-07-22 10:21
sorry to bother you two guys with such a newbie question.thanks a lot~ and in chinese  I want to say 赞！
