### ISSUE TITLE
console output I'm `fs` modules

### ISSUE THREAD

**Issue by shanvenleo** [casperjs/casperjs#1608] opened 2016-06-02 06:39 UTC
when I run any script by casperjs , It's console output: `I'm`fs`modules`, why?

**Comment by shanvenleo** [comment] 2016-06-02 06:46
I test 4 PCs ,have the same problem. Windows7&10
> >phantomjs --version
> 1.9.6
> >casperjs --version
> 1.1.1
> >casperjs sample.js
> I'm `fs` modules

**Comment by mickaelandrieu** [comment] 2016-06-02 10:51
Hi @shanvenleo would you mind to show us sample.js file content please?

**Comment by recipop** [comment] 2016-06-05 15:06
Same issue here, nothing to do with the input file as I've tried it and it works fine. Is it a broken dependency that's recently been upgraded?

**Comment by eagerowl** [comment] 2016-06-05 15:07
Same issue here, nothing to do with the input file as I've tried it and it works fine. Is it a broken dependency that's recently been upgraded?

**Comment by mickaelandrieu** [comment] 2016-06-05 15:30
@yoannmoinet any idea ? I don't use Windows :)

**Comment by eagerowl** [comment] 2016-06-05 15:46
I'm on OSX El Capitan and I'm getting the same problem, so might not be platform specific?

**Comment by eagerowl** [comment] 2016-06-05 15:48
<img width="605" alt="screen shot 2016-06-05 at 16 47 58" src="https://cloud.githubusercontent.com/assets/16610894/15806551/55c02dd0-2b3d-11e6-9f6b-51aeeca5c4db.png">

**Comment by mickaelandrieu** [comment] 2016-06-05 16:12
This is totaly `ìnsane` o_O the issue comes from ... `fs` module of nodejs => http://stackoverflow.com/questions/31572054/web-scrapping-with-casperjs-returns-strange-error-that-isnt-documented/33135476#33135476

``
npm uninstall fs
npm install -g fs
``

*[troll on] And they said node is suitable for professional stuff ...[troll off]*

**Comment by eagerowl** [comment] 2016-06-05 16:30
Yeah, I tried that but it didn't make any difference, is there a particular directory I need to do it in? It was my understanding that phantom and casper don't use node_modules? Probably wrong on that tbh!

**Comment by yoannmoinet** [comment] 2016-06-05 16:57
@mickaelandrieu nothing much I can do :smile: 
@eagerowl it looks like some local `npm install fs` was done and therefor Casper is using this instead of the native Node one.

I could look into the 3 tests failing on windows though, or are they known?

**Comment by eagerowl** [comment] 2016-06-05 21:05
Fixed by removing node_modules from my home directory and the npm global node_modules folder and re-installing.

**Comment by mickaelandrieu** [comment] 2016-06-05 21:37
@eagerowl any chance from our side to fix this bad behavior ? I mean I'm not a node expert (or even a good javascript developer tbh :) )

**Comment by eagerowl** [comment] 2016-06-05 22:08
@mickaelandrieu I wish I could suggest something and figure out what caused it but I've not got anything concrete. Might be worth checking the package includes, has a dependency been updated recently that's introduced a breaking change?

**Comment by mickaelandrieu** [comment] 2016-06-05 22:09
@eagerowl I've checked our [package.json](https://github.com/casperjs/casperjs/blob/master/package.json) file, we don't have any dependency ...

**Comment by eagerowl** [comment] 2016-06-05 22:11
Where does "fs" get referenced? Must be related to this in some way...

**Comment by istr** [comment] 2016-06-29 19:03
This does not occur using PhantomJS 2.1.1. This is a duplicate of #1276 where we have a test script attached.

**Comment by Morbit** [comment] 2016-10-29 21:41
I have the same problem in version 2.1.1

**Comment by mlalpho** [comment] 2016-12-13 04:40
If this is a duplicate and only present on PhantomJS 1.9* then can this and #340 be closed? 

If not and is confirmed to still be present and it's a node issue (can't fix in casperjs), then can someone document the weird behavior and submit a PR, so that there are no further duplicates?

**Comment by jefleponot** [comment] 2016-12-13 13:43
No more bug

**Closed by jefleponot** 2016-12-13 13:43 UTC
Labels: PhantomJS 1.9.x, Qualified

**Comment by shahidmau** [comment] 2017-08-08 14:12
I am also getting same error
phantomjs --version
2.1.1

casperjs --version
1.1.4

how to fix?
