### ISSUE TITLE
Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by jpca999** [casperjs/casperjs#1791] opened 2017-03-19 13:47 UTC
nsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.

when it calls this function it spits above error. : 

casper.then(function(){
    this.echo('underscore ='); 
    this.echo(_); 
}
fyi: lodash is already loaded, 

clientScripts:["plugins/jquery.js","plugins/lodash.js"]

and other functions are calling lodash and it works fine.

**Comment by kensoh** [comment] 2017-05-20 14:51
@jpca999 this looks like duplicated of https://github.com/casperjs/casperjs/issues/1792 and sounds like you are trying to use Lodash with CasperJS.

**Comment by kensoh** [comment] 2017-05-22 23:55
Closing this for now, the other duplicated issue #1792 not sure.. It looks like some conflict with Lodash's expected behavior when used together with CasperJS.

**Closed by kensoh** 2017-05-22 23:55 UTC
