### ISSUE TITLE
scrollToBottom throws an error

### ISSUE THREAD

**Issue by taymonbeal** [casperjs/casperjs#786] opened 2014-01-03 06:04 UTC
After loading a page and calling `this.scrollToBottom()`, the following error occurs:

```
CasperError: callUtils(scrollToBottom) with args  thrown an error: 'null' is not an object (evaluating 'document.body.scrollHeight')
  /home/me/casperjs/modules/casper.js:291 in callUtils
  /home/me/casperjs/modules/casper.js:1643 in scrollToBottom
  /home/me/Documents/myscript.js:29
  /home/me/casperjs/modules/casper.js:1553 in runStep
  /home/me/casperjs/modules/casper.js:399 in checkStep
```

**Comment by kensoh** [comment] 2017-05-22 19:46
@taymonbeal it's been some years, is this issue still happening for you? Not sure if current version works consistently in this case. I can only think of the page not yet loaded fully when the method is called. Adding explicit wait for maybe 30 seconds before calling that may help to isolate whether that is the cause.

**Comment by taymonbeal** [comment] 2017-05-22 19:54
I abandoned this project awhile ago. I might still have it around somewhere though.

**Comment by kensoh** [comment] 2017-05-22 22:06
Oh yep it has been 3 years.. If you found it but don't want to setup the latest CasperJS/PhantomJS etc, can paste the script here I can try to run your script to see if the error still happens.

**Comment by kensoh** [comment] 2017-06-02 02:50
Closing the issue for now as I am able to use scrolltobottom on a number of websites before without issue. But please reopen or raise a new issue if you still run into this in future. Thanks @taymonbeal for raising it!

**Closed by kensoh** 2017-06-02 02:50 UTC
